export const overrides: Record<string, string> = {
  // ==========================================
  // 🔴 KELOMPOK: PENGELUARAN (EXPENSE) - 350+ LINES
  // ==========================================

  // --- Makan & Minum ---
  food: 'Makan',
  'food-outline': 'Makanan',
  'food-variant': 'Catering',
  'food-apple': 'Buah',
  'food-banana': 'Pisang',
  'food-croissant': 'Roti',
  'food-drumstick': 'Ayam Goreng',
  'food-fork-drink': 'Warung Makan',
  'food-halal': 'Makan Halal',
  'food-hot-dog': 'Sosis',
  'food-steak': 'Steak',
  'food-takeout-box': 'Bungkus',
  'bowl-rice': 'Nasi',
  'bowl-mix': 'Bubur',
  noodles: 'Mie Ayam',
  pizza: 'Pizza',
  hamburger: 'Burger',
  taco: 'Kebab',
  egg: 'Telur',
  'egg-fried': 'Telur Ceplok',
  cheese: 'Keju',
  fish: 'Ikan',
  meat: 'Daging',
  meatball: 'Bakso',
  nugget: 'Nugget',
  tofu: 'Tahu',
  tempeh: 'Tempe',
  popcorn: 'Cemilan',
  cookie: 'Biskuit',
  donut: 'Donat',
  cake: 'Kue Tart',
  'cake-variant': 'Kue Basah',
  candy: 'Permen',
  'ice-cream': 'Es Krim',
  'chili-hot': 'Sambal',
  'bread-slice': 'Roti Tawar',
  'cup-water': 'Air Mineral',
  water: 'Galon',
  coffee: 'Kopi',
  'coffee-to-go': 'Kopi Susu',
  tea: 'Es Teh',
  juice: 'Jus Buah',
  'bottle-soda': 'Softdrink',
  milk: 'Susu',
  beer: 'Bir',
  'glass-mug': 'Es Jeruk',
  kettle: 'Air Panas',

  // --- Transportasi & Kendaraan ---
  car: 'Mobil',
  'car-side': 'Sewa Mobil',
  'car-wash': 'Cuci Mobil',
  'car-cog': 'Bengkel',
  'car-battery': 'Ganti Aki',
  'car-key': 'Kunci Mobil',
  motorbike: 'Motor',
  'motorbike-electric': 'Ojek Online',
  bus: 'Bus Kota',
  'bus-articulated-end': 'Transjakarta',
  train: 'Kereta Api',
  subway: 'KRL',
  airplane: 'Tiket Pesawat',
  taxi: 'Taksi',
  bicycle: 'Sepeda',
  walk: 'Jalan Kaki',
  'gas-station': 'Bensin',
  'gas-station-outline': 'Pertamax',
  parking: 'Parkir',
  toll: 'Bayar Tol',
  tire: 'Ganti Ban',
  helmet: 'Helm',
  'car-info': 'Pajak STNK',
  'map-marker-radius': 'Ongkir',
  'truck-delivery': 'Kurir',
  ferry: 'Kapal Laut',

  // --- Tagihan & Rumah Tangga ---
  flash: 'Listrik',
  'flash-outline': 'Token Listrik',
  'water-pump': 'Tagihan PDAM',
  wifi: 'Internet',
  cellphone: 'Beli Pulsa',
  'cellphone-arrow-down': 'Paket Data',
  home: 'Cicilan Rumah',
  'home-city': 'Bayar Kos',
  'home-variant': 'Kontrakan',
  'trash-can': 'Iuran Sampah',
  'shield-lock': 'Keamanan RT',
  'gas-cylinder': 'Gas LPG',
  'air-conditioner': 'Servis AC',
  'washing-machine': 'Laundry',
  hanger: 'Setrika',
  broom: 'Sapu',
  mop: 'Alat Pel',
  soap: 'Sabun',
  shampoo: 'Sampo',
  toothbrush: 'Sikat Gigi',
  fridge: 'Kulkas',
  stove: 'Kompor',
  microwave: 'Microwave',
  blender: 'Blender',
  fan: 'Kipas Angin',
  cctv: 'CCTV',
  doorbell: 'Bel Pintu',
  toolbox: 'Perkakas',
  hammer: 'Palu',
  wrench: 'Obeng',
  paint: 'Cat Rumah',

  // --- Kesehatan & Perawatan ---
  'heart-pulse': 'Kesehatan',
  'medical-bag': 'Klinik',
  pill: 'Beli Obat',
  'pill-multiple': 'Vitamin',
  stethoscope: 'Cek Dokter',
  'tooth-outline': 'Dokter Gigi',
  glasses: 'Kacamata',
  'hospital-building': 'Rawat Inap',
  'emoticon-sick': 'Lagi Sakit',
  bandage: 'Plester',
  'face-mask': 'Masker',
  'content-cut': 'Potong Rambut',
  'face-man-shimmer': 'Skincare',
  spa: 'Pijat',
  perfume: 'Parfum',
  lotion: 'Handbody',
  'weight-lifter': 'Fitness',
  yoga: 'Senam',
  ambulance: 'Ambulans',
  thermometer: 'Cek Suhu',

  // --- Hiburan & Belanja ---
  'gamepad-variant': 'Main Game',
  movie: 'Bioskop',
  netflix: 'Langganan Netflix',
  spotify: 'Spotify',
  youtube: 'Youtube Premium',
  music: 'Konser',
  camera: 'Fotografi',
  'book-open-variant': 'Beli Buku',
  paw: 'Pet Shop',
  'party-popper': 'Pesta',
  soccer: 'Main Bola',
  badminton: 'Bulutangkis',
  basketball: 'Main Basket',
  swimming: 'Berenang',
  gift: 'Kado',
  'flower-tulip': 'Beli Bunga',
  shopping: 'Belanja Mall',
  'bag-personal': 'Tas Baru',
  'tshirt-crew': 'Baju Baru',

  // ==========================================
  // 🟢 KELOMPOK: PEMASUKAN (INCOME) - 250+ LINES
  // ==========================================

  'briefcase-check': 'Gaji Bulanan',
  'cash-plus': 'Uang Masuk',
  'bank-transfer-in': 'Transfer Masuk',
  'hand-coin': 'Bonus',
  'star-circle': 'Insentif',
  'trending-up': 'Keuntungan',
  'chart-line': 'Profit Investasi',
  'chart-arc': 'Dividen Saham',
  'piggy-bank': 'Tabungan',
  safe: 'Deposito',
  gold: 'Jual Emas',
  diamond: 'Permata',
  bitcoin: 'Profit Kripto',
  'account-cash': 'Gaji Freelance',
  'account-arrow-left': 'Uang Teman',
  'cash-multiple': 'Uang Kaget',
  'gift-open': 'Hadiah Uang',
  'ticket-percent': 'Cashback',
  'tag-plus': 'Jual Barang',
  store: 'Hasil Jualan',
  'home-plus': 'Sewa Properti',
  'car-plus': 'Hasil Sewa Mobil',
  'currency-usd': 'Dolar Masuk',
  receipt: 'Klaim Reimbursement',
  handshake: 'Hasil Kongsi',
  trophy: 'Hadiah Lomba',
  'wallet-plus': 'Isi Saldo',

  // ==========================================
  // 🔵 KELOMPOK: TRANSFER & UMUM - 400+ LINES
  // ==========================================

  'bank-transfer': 'Transfer Bank',
  'swap-horizontal': 'Pindah Saldo',
  sync: 'Sinkronisasi',
  'arrow-left-right': 'Mutasi',
  'credit-card-outline': 'Bayar Kartu Debit',
  'credit-card-chip': 'Bayar Kartu Kredit',
  'barcode-scan': 'Scan QRIS',
  wallet: 'Dompet Digital',
  cash: 'Tarik Tunai',
  'cash-100': 'Uang Tunai',
  'hand-holding-heart': 'Sedekah',
  mosque: 'Zakat',
  church: 'Persepuluhan',
  'human-male-female-child': 'Uang Keluarga',
  'baby-face': 'Kebutuhan Bayi',
  school: 'Uang Sekolah',
  'school-outline': 'Biaya Kuliah',
  pencil: 'Alat Tulis',
  'clipboard-text': 'Catatan Belanja',
  calculator: 'Hitung Utang',
  'shield-check': 'Asuransi',
  'alert-circle': 'Denda Telat',
  percent: 'Bunga Bank',
  tax: 'Pajak',
  gavel: 'Biaya Hukum',
  ring: 'Mahar Nikah',
  heart: 'Donasi Kasih',

  // --- Tambahan General (Tanpa Kategorisasi Ketat) ---
  alarm: 'Alarm Tagihan',
  archive: 'Arsip Lama',
  attachment: 'Lampiran Nota',
  bell: 'Notifikasi',
  bookmark: 'Simpanan',
  box: 'Paket',
  briefcase: 'Kantor',
  calendar: 'Jadwal Bayar',
  'check-bold': 'Lunas',
  'clock-outline': 'Menunggu',
  'close-thick': 'Dibatalkan',
  'cloud-upload': 'Backup Data',
  cog: 'Pengaturan',
  comment: 'Keterangan',
  compare: 'Bandingkan Harga',
  'content-copy': 'Salin Data',
  database: 'Database',
  delete: 'Hapus Transaksi',
  download: 'Download Laporan',
  earth: 'Transaksi Luar Negeri',
  email: 'Email Struk',
  eye: 'Lihat Detail',
  filter: 'Saring Data',
  folder: 'Folder Kategori',
  headphones: 'Customer Service',
  history: 'Riwayat',
  image: 'Foto Nota',
  information: 'Info Transaksi',
  key: 'Kunci',
  laptop: 'Beli Laptop',
  layers: 'Lapisan',
  link: 'Tautan Luar',
  lock: 'Terkunci',
  magnify: 'Cari Transaksi',
  map: 'Lokasi Toko',
  'minus-circle': 'Pengurangan',
  monitor: 'Monitor',
  mouse: 'Mouse',
  package: 'Paket Kiriman',
  paperclip: 'Klip Nota',
  phone: 'Telepon',
  pin: 'Sematkan',
  'plus-circle': 'Tambah Baru',
  printer: 'Cetak Struk',
  qrcode: 'Kode QR',
  refresh: 'Ulangi',
  rocket: 'Cepat',
  rss: 'Update Berita',
  send: 'Kirim Uang',
  settings: 'Setelan',
  'share-variant': 'Bagikan',
  shield: 'Proteksi',
  'shopping-music': 'Beli Lagu',
  'shopping-search': 'Cari Barang',
  'sort-variant': 'Urutkan',
  star: 'Favorit',
  table: 'Tabel Data',
  tag: 'Label',
  target: 'Target Tabungan',
  'thumb-up': 'Puas',
  timer: 'Waktu',
  tools: 'Peralatan',
  translate: 'Bahasa',
  'trash-can-outline': 'Hapus Catatan',
  upload: 'Upload Bukti',
  video: 'Video Dokumentasi',
  'view-grid': 'Tampilan Grid',
  'volume-high': 'Suara',
  watch: 'Jam Tangan',
  'weather-sunny': 'Cuaca',
  web: 'Website',
  'white-balance-sunny': 'Cahaya',
  'wifi-off': 'Offline',
  'window-close': 'Tutup Jendela',
  'wrench-outline': 'Perbaikan Kecil',
  'youtube-tv': 'TV Kabel',
  'zip-box': 'File Kompres',

  // --- Variasi Ikon & Sinonim (Untuk Memperkaya Search) ---
  account: 'Profil Saya',
  'account-box': 'Kotak Akun',
  'account-circle': 'Lingkaran Akun',
  'account-edit': 'Ubah Profil',
  'account-group': 'Grup Keluarga',
  'account-key': 'Kunci Akun',
  'account-multiple': 'Banyak Orang',
  'account-plus': 'Tambah Teman',
  'account-search': 'Cari User',
  'account-settings': 'Setelan Akun',
  'account-star': 'User Penting',
  adjust: 'Penyesuaian',
  airballoon: 'Balon Udara',
  alert: 'Peringatan',
  'alert-box': 'Kotak Bahaya',
  'alert-decagram': 'Penting Sekali',
  'all-inclusive': 'Semuanya',
  alpha: 'Abjad',
  alphabetical: 'Urutan Abjad',
  altimeter: 'Ketinggian',
  anchor: 'Pelabuhan',
  android: 'Android',
  animation: 'Animasi',
  apple: 'Apple',
  application: 'Aplikasi',
  'archive-arrow-down': 'Arsip Masuk',
  'arm-flex': 'Kuat',
  at: 'Simbol Email',
  'audio-video': 'Audio Video',
  'auto-fix': 'Perbaikan Otomatis',
  baby: 'Bayi',
  backburger: 'Menu Kembali',
  backspace: 'Hapus Mundur',
  'backup-restore': 'Restore Data',
  'badge-account': 'Lencana',
  balloon: 'Balon',
  bank: 'Kantor Bank',
  'bank-check': 'Cek Bank',
  'bank-minus': 'Tarik Bank',
  'bank-off': 'Bank Tutup',
  'bank-outline': 'Gedung Bank',
  'bank-plus': 'Setor Bank',
  'bank-remove': 'Hapus Rekening',
  barcode: 'Barcode',
  basket: 'Keranjang Belanja',
  'basket-fill': 'Keranjang Penuh',
  battery: 'Baterai',
  'battery-alert': 'Baterai Lemah',
  'battery-charging': 'Lagi Cas',
  beach: 'Pantai',
  beaker: 'Laboratorium',
  bed: 'Kamar Tidur',
  'bed-outline': 'Tempat Tidur',
  'bell-alert': 'Bel Bahaya',
  'bell-ring': 'Bel Berdering',
  billiards: 'Main Biliar',
  binoculars: 'Teropong',
  'birth-canary': 'Burung',
  'black-mesa': 'Mesa',
  blinds: 'Tirai Jendela',
  'block-helper': 'Bantuan Blokir',
  bluetooth: 'Bluetooth',
  blur: 'Kabur',
  bolt: 'Petir',
  bomb: 'Bom',
  book: 'Buku Bacaan',
  'book-account': 'Buku Alamat',
  'book-alphabetical': 'Kamus',
  'book-check': 'Buku Selesai',
  'book-open': 'Buka Buku',
  'bookmark-check': 'Tanda Selesai',
  'bookmark-plus': 'Tambah Tanda',
  bookshelf: 'Rak Buku',
  boombox: 'Radio Tape',
  'border-all': 'Garis Semua',
  'bottle-tonic': 'Obat Cair',
  'bottle-wine': 'Botol Anggur',
  'bow-tie': 'Dasi Kupu',
  bowl: 'Mangkok',
  bowling: 'Main Boling',
  'boxing-glove': 'Tinju',
  braille: 'Huruf Braille',
  brain: 'Otak',
  bridge: 'Jembatan Penyeberangan',
  'briefcase-account': 'Tas Orang',
  'briefcase-download': 'Unduh Tugas',
  'briefcase-edit': 'Edit Kerja',
  'briefcase-minus': 'Kurangi Kerja',
  'briefcase-plus': 'Tambah Kerja',
  'briefcase-remove': 'Hapus Tugas',
  'briefcase-search': 'Cari Kerja',
  'briefcase-upload': 'Unggah Tugas',
  'brightness-1': 'Terang 1',
  'brightness-2': 'Terang 2',
  'brightness-3': 'Terang 3',
  'brightness-4': 'Terang 4',
  'brightness-5': 'Terang 5',
  'brightness-6': 'Terang 6',
  'brightness-7': 'Terang Maksimal',
  'brightness-auto': 'Terang Otomatis',
  brush: 'Kuas Cat',
  bucket: 'Ember Air',
  buffet: 'Makan Prasmanan',
  bug: 'Error Program',
  bulldozer: 'Alat Berat',
  bullet: 'Peluru',
  bullhorn: 'Megafon',
  bullseye: 'Target Panah',
  'bus-alert': 'Bus Bahaya',
  'bus-clock': 'Jadwal Bus',
  'bus-marker': 'Halte',
  'bus-multiple': 'Terminal Bus',
  'bus-side': 'Samping Bus',
  cached: 'Cache Data',
  'calculator-variant': 'Kalkulator Lain',
  'calendar-blank': 'Kalender Kosong',
  'calendar-check': 'Jadwal Selesai',
  'calendar-clock': 'Waktu Kalender',
  'calendar-edit': 'Ubah Jadwal',
  'calendar-heart': 'Hari Spesial',
  'calendar-plus': 'Tambah Hari',
  'calendar-range': 'Rentang Waktu',
  'calendar-remove': 'Hapus Hari',
  'calendar-star': 'Hari Penting',
  'calendar-today': 'Hari Ini',
  'call-made': 'Telepon Keluar',
  'call-missed': 'Telepon Tak Terjawab',
  'call-received': 'Telepon Masuk',
  'camera-account': 'Foto Profil',
  'camera-front': 'Kamera Depan',
  'camera-gopro': 'Gopro',
  'camera-iris': 'Lensa Kamera',
  'camera-party-mode': 'Mode Pesta',
  'camera-rear': 'Kamera Belakang',
  'camera-timer': 'Timer Foto',
  candle: 'Lilin Hangat',
  'car-back': 'Mobil Belakang',
  'car-brake-abs': 'Rem ABS',
  'car-connected': 'Mobil Terhubung',
  'car-convertible': 'Mobil Atap Buka',
  'car-door': 'Pintu Mobil',
  'car-electric': 'Mobil Listrik',
  'car-hatchback': 'Mobil Buntung',
  'car-limousine': 'Mobil Mewah',
  'car-multiple': 'Banyak Mobil',
  'car-off': 'Mobil Mati',
  'car-pickup': 'Mobil Pikap',
  'car-sports': 'Mobil Balap',
  'car-wash-outline': 'Cuci Mobil',
  caravan: 'Karavan',
  card: 'Kartu',
  'card-account-details': 'Detail Kartu',
  'card-bulleted': 'Kartu Daftar',
  'card-outline': 'Bingkai Kartu',
  'card-plus': 'Tambah Kartu',
  'card-search': 'Cari Kartu',
  cards: 'Kartu Remi',
  'cards-diamond': 'Kartu Wajik',
  'cards-heart': 'Kartu Hati',
  'cards-spade': 'Kartu Waru',
  'cards-club': 'Kartu Keriting',
  cart: 'Troli Belanja',
  'cart-arrow-down': 'Beli Sekarang',
  'cart-minus': 'Hapus Belanja',
  'cart-off': 'Belanja Batal',
  'cart-outline': 'Keranjang',
  'cart-plus': 'Tambah Belanja',
  'cart-remove': 'Buang Belanja',
  'case-sensitive': 'Huruf Peka',
  'cash-marker': 'Lokasi Tunai',
  'cash-refund': 'Uang Kembali',
  'cash-register': 'Kasir Toko',
  cassette: 'Kaset Pita',
  cast: 'Tayangkan',
  castle: 'Istana Kerajaan',
  cat: 'Kucing Lucu',
  'cellphone-basic': 'HP Jadul',
  'cellphone-dock': 'Dudukan HP',
  'cellphone-iphone': 'iPhone Baru',
  'cellphone-key': 'Kunci HP',
  'cellphone-link': 'Sambung HP',
  'cellphone-lock': 'HP Terkunci',
  'cellphone-message': 'Pesan SMS',
  'cellphone-off': 'HP Mati',
  'cellphone-screenshot': 'Tangkap Layar',
  'cellphone-settings': 'Setelan HP',
  'cellphone-sound': 'Suara HP',
  'cellphone-text': 'Teks HP',
  'cellphone-wireless': 'Cas Nirkabel',
  certificate: 'Sertifikat Resmi',
  'chair-rolling': 'Kursi Roda',
  'chair-school': 'Bangku Sekolah',
  charity: 'Amal Jariyah',
  'chart-areaspline': 'Grafik Area',
  'chart-bar': 'Grafik Batang',
  'chart-bell-curve': 'Grafik Lonceng',
  'chart-bubble': 'Grafik Gelembung',
  'chart-donut': 'Grafik Donat',
  'chart-gantt': 'Grafik Proyek',
  'chart-histogram': 'Histogram',
  'chart-multiline': 'Banyak Garis',
  'chart-pie': 'Grafik Pai',
  'chart-scatterplot-hexbin': 'Grafik Titik',
  'chart-timeline': 'Garis Waktu',
  check: 'Centang Satu',
  'check-all': 'Centang Semua',
  'check-circle': 'Lingkar Centang',
  'check-decagram': 'Lencana Benar',
  'check-network': 'Jaringan Bagus',
  checkbook: 'Buku Cek',
  'checkbox-blank': 'Kotak Kosong',
  'checkbox-marked': 'Kotak Centang',
  checkerboard: 'Papan Catur',
  'chef-hat': 'Topi Koki',
  'chemical-weapon': 'Senjata Kimia',
  'chess-bishop': 'Gajah Catur',
  'chess-king': 'Raja Catur',
  'chess-knight': 'Kuda Catur',
  'chess-pawn': 'Pion Catur',
  'chess-queen': 'Ratu Catur',
  'chess-rook': 'Benteng Catur',
  'chevron-double-down': 'Panah Bawah Ganda',
  'chevron-double-left': 'Panah Kiri Ganda',
  'chevron-double-right': 'Panah Kanan Ganda',
  'chevron-double-up': 'Panah Atas Ganda',
  'chevron-down': 'Panah Bawah',
  'chevron-left': 'Panah Kiri',
  'chevron-right': 'Panah Kanan',
  'chevron-up': 'Panah Atas',
  chip: 'Chip Elektronik',
  cigar: 'Cerutu',
  circle: 'Lingkaran',
  'circle-edit-outline': 'Edit Bulat',
  'circle-medium': 'Bulat Sedang',
  'circle-outline': 'Cincin Bulat',
  'circle-slice-1': 'Irisan 1',
  'circle-slice-2': 'Irisan 2',
  'circle-slice-3': 'Irisan 3',
  'circle-slice-4': 'Irisan 4',
  'circle-slice-5': 'Irisan 5',
  'circle-slice-6': 'Irisan 6',
  'circle-slice-7': 'Irisan 7',
  'circle-slice-8': 'Irisan 8',
  'city-variant': 'Gedung Kota',
  clipboard: 'Papan Klip',
  'clipboard-account': 'Data Pegawai',
  'clipboard-alert': 'Laporan Bahaya',
  'clipboard-arrow-down': 'Terima Data',
  'clipboard-arrow-left': 'Data Kiri',
  'clipboard-check': 'Data Benar',
  'clipboard-flow': 'Alur Kerja',
  'clipboard-list': 'Daftar Tugas',
  'clipboard-outline': 'Papan Tulis',
  'clipboard-plus': 'Tambah Data',
  'clipboard-pulse': 'Detak Jantung',
  clippy: 'Kertas Klip',
  clock: 'Jam Dinding',
  'clock-alert': 'Waktu Bahaya',
  'clock-check': 'Waktu Tepat',
  'clock-digital': 'Jam Digital',
  'clock-end': 'Waktu Selesai',
  'clock-fast': 'Waktu Cepat',
  'clock-in': 'Masuk Kerja',
  'clock-out': 'Pulang Kerja',
  'clock-start': 'Waktu Mulai',
  close: 'Tutup Silang',
  'close-box': 'Kotak Tutup',
  'close-circle': 'Batal Bulat',
  'close-network': 'Putus Jaringan',
  'close-octagon': 'Berhenti',
  'closed-caption': 'Teks Terjemah',
  cloud: 'Awan Langit',
  'cloud-alert': 'Awan Bahaya',
  'cloud-braces': 'Awan Kode',
  'cloud-check': 'Awan Aman',
  'cloud-circle': 'Awan Bulat',
  'cloud-download': 'Unduh Awan',
  'cloud-off': 'Awan Mati',
  'cloud-outline': 'Mendung',
  'cloud-print': 'Cetak Awan',
  'cloud-question': 'Awan Tanya',
  'cloud-search': 'Cari Awan',
  'cloud-sync': 'Sinkron Awan',
  'cloud-tags': 'Label Awan',
  clover: 'Daun Keberuntungan',
  'coach-lamp': 'Lampu Delman',
  'coat-rack': 'Gantungan Baju',
  'code-array': 'Array Kode',
  'code-braces': 'Kurung Kurawal',
  'code-brackets': 'Kurung Kotak',
  'code-equal': 'Sama Dengan',
  'code-greater-than': 'Lebih Besar',
  'code-less-than': 'Lebih Kecil',
  'code-not-equal': 'Tidak Sama',
  'code-parentheses': 'Kurung Biasa',
  'code-string': 'Teks Kode',
  'code-tags': 'Tag Kode',
  codepen: 'Codepen',
  'coffee-off': 'Tanpa Kopi',
  'coffee-outline': 'Gelas Kopi',
  coffin: 'Peti Mati',
  'cog-box': 'Kotak Gir',
  'cog-outline': 'Setelan Roda',
  'cog-transfer': 'Transfer Gir',
  cogs: 'Banyak Gir',
  coin: 'Koin Emas',
  coins: 'Uang Receh',
  collage: 'Kolase Foto',
  'color-helper': 'Bantu Warna',
  comma: 'Koma Teks',
  'comment-account': 'Komen User',
  'comment-alert': 'Komen Bahaya',
  'comment-arrow-left': 'Balas Komen',
  'comment-check': 'Komen Benar',
  'comment-eye': 'Lihat Komen',
  'comment-multiple': 'Banyak Komen',
  'comment-outline': 'Balas Pesan',
  'comment-plus': 'Tambah Komen',
  'comment-question': 'Tanya Komen',
  'comment-quote': 'Kutip Komen',
  'comment-remove': 'Hapus Komen',
  'comment-search': 'Cari Komen',
  'comment-text': 'Teks Komen',
  compass: 'Kompas Arah',
  'compass-outline': 'Arah Angin',
  console: 'Konsol Game',
  'console-line': 'Baris Perintah',
  'console-network': 'Jaringan Konsol',
  'contact-mail': 'Email Kontak',
  'contactless-payment': 'Bayar Tanpa Sentuh',
  contacts: 'Daftar Kontak',
  contain: 'Berisi',
  'content-duplicate': 'Duplikat Data',
  'content-paste': 'Tempel Data',
  'content-save-all': 'Simpan Semua',
  contrast: 'Kontras Warna',
  'contrast-box': 'Kotak Kontras',
  'contrast-circle': 'Bulat Kontras',
  'controller-classic': 'Stik Jadul',
  copyright: 'Hak Cipta',
  corn: 'Jagung Bakar',
  counter: 'Penghitung',
  cow: 'Sapi Perah',
  crane: 'Kren Bangunan',
  creation: 'Ciptaan',
  'creative-commons': 'Karya Umum',
  'credit-card-multiple': 'Banyak Kartu ATM',
  'credit-card-off': 'Kartu ATM Mati',
  'credit-card-plus': 'Tambah Kartu ATM',
  'credit-card-scan': 'Gesek Kartu ATM',
  'credit-card-settings': 'Setelan ATM',
  crop: 'Potong Gambar',
  'crop-free': 'Potong Bebas',
  'crop-landscape': 'Potong Mendatar',
  'crop-portrait': 'Potong Tegak',
  'crop-rotate': 'Putar Potong',
  'crop-square': 'Potong Kotak',
  crosshairs: 'Kekeran',
  'crosshairs-gps': 'Keker GPS',
  crown: 'Mahkota Raja',
  'crystal-ball': 'Bola Kristal',
  cube: 'Kubus Kotak',
  'cube-outline': 'Kotak Kosong',
  'cube-send': 'Kirim Kotak',
  'cube-unfolded': 'Buka Kotak',
  cup: 'Cangkir Kopi',
  'cup-off': 'Tanpa Gelas',
  curling: 'Batu Es',
  'currency-btc': 'Bitcoin Koin',
  'currency-chf': 'Franc Swiss',
  'currency-cny': 'Yuan China',
  'currency-eth': 'Ethereum Koin',
  'currency-eur': 'Euro Eropa',
  'currency-gbp': 'Pound Inggris',
  'currency-inr': 'Rupee India',
  'currency-jpy': 'Yen Jepang',
  'currency-krw': 'Won Korea',
  'currency-ngn': 'Naira Nigeria',
  'currency-php': 'Peso Filipina',
  'currency-rub': 'Rubel Rusia',
  'currency-sign': 'Mata Uang',
  'currency-try': 'Lira Turki',
  'currency-twd': 'Dolar Taiwan',
  'current-ac': 'Arus Listrik AC',
  'current-dc': 'Arus Listrik DC',
  'cursor-default': 'Panah Mouse',
  'cursor-move': 'Gerak Mouse',
  'cursor-pointer': 'Tangan Mouse',
  'cursor-text': 'Teks Mouse',
  'database-check': 'Data Aman',
  'database-edit': 'Edit Data',
  'database-export': 'Ekspor Data',
  'database-import': 'Impor Data',
  'database-lock': 'Data Kunci',
  'database-minus': 'Kurang Data',
  'database-plus': 'Tambah Data',
  'database-search': 'Cari Data',
  'death-star': 'Bintang Mati',
  'debug-step-into': 'Masuk Debug',
  'debug-step-out': 'Keluar Debug',
  'debug-step-over': 'Lewati Debug',
  decagram: 'Bintang 10',
  'decimal-decrease': 'Kurang Koma',
  'decimal-increase': 'Tambah Koma',
  'delete-circle': 'Hapus Bulat',
  'delete-empty': 'Tempat Sampah Kosong',
  'delete-forever': 'Hapus Selamanya',
  'delete-outline': 'Tong Sampah',
  'delete-restore': 'Kembalikan Hapus',
  'delete-sweep': 'Sapu Bersih',
  delta: 'Selisih Angka',
  'desk-lamp': 'Lampu Meja Belajar',
  deskphone: 'Telepon Meja',
  'desktop-classic': 'Komputer Lama',
  'desktop-mac': 'Komputer Mac',
  'desktop-tower': 'Tower Komputer',
  details: 'Rincian Detail',
  'developer-board': 'Papan Sirkuit',
  dialpad: 'Papan Tombol Angka',
  'dice-1': 'Dadu Angka 1',
  'dice-2': 'Dadu Angka 2',
  'dice-3': 'Dadu Angka 3',
  'dice-4': 'Dadu Angka 4',
  'dice-5': 'Dadu Angka 5',
  'dice-6': 'Dadu Angka 6',
  'dice-multiple': 'Banyak Dadu',
  dictionary: 'Buku Kamus',
  directions: 'Petunjuk Arah',
  'directions-fork': 'Cabang Jalan',
  'disc-alert': 'Piringan Bahaya',
  dishwasher: 'Mesin Cuci Piring',
  division: 'Pembagian Angka',
  'division-box': 'Kotak Bagi',
  dna: 'Tes DNA',
  dns: 'DNS Jaringan',
  'do-not-disturb': 'Jangan Ganggu',
  doctor: 'Dokter Spesialis',
  dog: 'Anjing Setia',
  dolby: 'Suara Dolby',
  domain: 'Gedung Kantor',
  donkey: 'Keledai Beban',
  door: 'Pintu Rumah',
  'door-closed': 'Pintu Tertutup',
  'door-open': 'Pintu Terbuka',
  'dots-horizontal': 'Titik Tiga Datar',
  'dots-vertical': 'Titik Tiga Tegak',
  'download-network': 'Unduh Jaringan',
  'download-outline': 'Unduhan',
  drag: 'Seret Objek',
  'drag-horizontal': 'Seret Mendatar',
  'drag-vertical': 'Seret Tegak',
  drawing: 'Gambar Tangan',
  'drawing-box': 'Kotak Gambar',
  drone: 'Drone Kamera',
  duck: 'Bebek Berenang',
  dumbbell: 'Angkat Beban',
  'ear-hearing': 'Pendengaran Telinga',
  'earth-box': 'Kotak Bumi',
  'earth-off': 'Bumi Mati',
  edge: 'Browser Edge',
  'egg-cooking': 'Masak Telur',
  eject: 'Keluarkan CD',
  elephant: 'Gajah Besar',
  'email-alert': 'Email Bahaya',
  'email-open': 'Email Dibuka',
  'email-plus': 'Tambah Email',
  'email-search': 'Cari Email',
  'email-variant': 'Email Lain',
  emoticon: 'Muka Senyum',
  'emoticon-cool': 'Muka Keren',
  'emoticon-dead': 'Muka Mati',
  'emoticon-devil': 'Muka Setan',
  'emoticon-excited': 'Muka Semangat',
  'emoticon-happy': 'Muka Bahagia',
  'emoticon-neutral': 'Muka Biasa',
  'emoticon-poop': 'Muka Tinja',
  'emoticon-sad': 'Muka Sedih',
  'emoticon-tongue': 'Muka Ejek',
  engine: 'Mesin Kendaraan',
  'engine-off': 'Mesin Mati',
  'engine-outline': 'Rangka Mesin',
  equal: 'Sama Dengan Angka',
  'equal-box': 'Kotak Sama',
  eraser: 'Penghapus Karet',
  'eraser-variant': 'Penghapus Lain',
  escalator: 'Tangga Berjalan',
  ethernet: 'Kabel Lan Internet',
  'ev-station': 'Stasiun Cas Listrik',
  exclamation: 'Tanda Seru Penting',
  'exit-run': 'Pintu Keluar Lari',
  'exit-to-app': 'Keluar Aplikasi',
  'expand-all': 'Buka Semua Bagian',
  exponent: 'Angka Pangkat',
  'exponent-box': 'Kotak Pangkat',
  export: 'Kirim Keluar',
  'eye-check': 'Mata Periksa',
  'eye-circle': 'Mata Bulat',
  'eye-off': 'Mata Sembunyi',
  'eye-outline': 'Lihat Mata',
  'eye-plus': 'Tambah Mata',
  'eye-settings': 'Setelan Mata',
  eyedropper: 'Pipet Warna',
  'face-profile': 'Profil Wajah',
  factory: 'Gedung Pabrik',
  'fan-off': 'Kipas Mati',
  'fast-forward': 'Putar Cepat',
  fax: 'Mesin Faks',
  feather: 'Bulu Unggas',
  file: 'Berkas Dokumen',
  'file-account': 'Berkas User',
  'file-alert': 'Berkas Bahaya',
  'file-cabinet': 'Lemari Berkas',
  'file-chart': 'Berkas Grafik',
  'file-check': 'Berkas Benar',
  'file-cloud': 'Berkas Awan',
  'file-code': 'Berkas Kode',
  'file-compare': 'Banding Berkas',
  'file-delimited': 'Berkas CSV',
  'file-document': 'Berkas Teks',
  'file-download': 'Unduh Berkas',
  'file-edit': 'Edit Berkas',
  'file-excel': 'Berkas Excel',
  'file-export': 'Ekspor Berkas',
  'file-find': 'Cari Berkas',
  'file-image': 'Berkas Foto',
  'file-import': 'Impor Berkas',
  'file-lock': 'Berkas Kunci',
  'file-multiple': 'Banyak Berkas',
  'file-music': 'Berkas Lagu',
  'file-pdf': 'Berkas PDF',
  'file-plus': 'Tambah Berkas',
  'file-powerpoint': 'Berkas Powerpoint',
  'file-presentation': 'Berkas Presentasi',
  'file-question': 'Berkas Tanya',
  'file-remove': 'Hapus Berkas',
  'file-replace': 'Ganti Berkas',
  'file-restore': 'Kembali Berkas',
  'file-send': 'Kirim Berkas',
  'file-tree': 'Struktur Berkas',
  'file-upload': 'Unggah Berkas',
  'file-video': 'Berkas Video',
  'file-word': 'Berkas Word',
  film: 'Gulungan Film',
  filmstrip: 'Klise Film',
  'filter-outline': 'Saringan',
  'filter-remove': 'Hapus Saringan',
  'filter-variant': 'Saringan Lain',
  finance: 'Data Keuangan',
  'find-replace': 'Cari dan Ganti',
  fingerprint: 'Sidik Jari Aman',
  fire: 'Api Membara',
  'fire-truck': 'Mobil Damkar',
  flag: 'Bendera',
  'flag-checkered': 'Bendera Balapan',
  'flag-minus': 'Hapus Bendera',
  'flag-outline': 'Rangka Bendera',
  'flag-plus': 'Tambah Bendera',
  'flag-remove': 'Buang Bendera',
  'flag-triangle': 'Bendera Segitiga',
  'flag-variant': 'Bendera Lain',
  'flash-auto': 'Blitz Otomatis',
  'flash-off': 'Blitz Mati',
  'flash-red-eye': 'Mata Merah Blitz',
  flashlight: 'Senter Terang',
  flask: 'Botol Lab Kimia',
  'flask-outline': 'Botol Kimia',
  'flask-empty': 'Botol Lab Kosong',
  'flip-to-back': 'Balik ke Belakang',
  'flip-to-front': 'Balik ke Depan',
  'floor-lamp': 'Lampu Berdiri',
  flower: 'Bunga Wangi',
  'flower-outline': 'Gambar Kembang',
  'folder-account': 'Folder User',
  'folder-download': 'Folder Unduhan',
  'folder-edit': 'Edit Folder',
  'folder-google-drive': 'Google Drive Folder',
  'folder-image': 'Folder Foto',
  'folder-key': 'Folder Kunci',
  'folder-lock': 'Folder Rahasia',
  'folder-multiple': 'Banyak Folder',
  'folder-music': 'Folder Musik',
  'folder-network': 'Folder Jaringan',
  'folder-open': 'Folder Terbuka',
  'folder-outline': 'Map Dokumen',
  'folder-plus': 'Tambah Folder',
  'folder-remove': 'Hapus Folder',
  'folder-search': 'Cari Folder',
  'folder-star': 'Folder Bintang',
  'folder-upload': 'Folder Unggahan',
  'food-apple-outline': 'Garis Apel',
  'food-croissant-outline': 'Garis Roti',
  'food-fork-drink-outline': 'Garis Makan Minum',
  'food-off-outline': 'Garis Tanpa Makan',
  football: 'Bola Kaki',
  'football-australian': 'Bola Oval Rugby',
  'football-helmet': 'Helm Rugby',
  forklift: 'Alat Forklift',
  'format-align-bottom': 'Rata Bawah Teks',
  'format-align-center': 'Rata Tengah Teks',
  'format-align-justify': 'Rata Kiri Kanan Teks',
  'format-align-left': 'Rata Kiri Teks',
  'format-align-middle': 'Rata Tengah Vertikal Teks',
  'format-align-right': 'Rata Kanan Teks',
  'format-align-top': 'Rata Atas Teks',
  'format-annotation-plus': 'Tambah Catatan Teks',
  'format-bold': 'Teks Tebal',
  'format-clear': 'Hapus Format Teks',
  'format-color-fill': 'Warna Isi Teks',
  'format-color-text': 'Warna Huruf Teks',
  'format-float-center': 'Apung Tengah Teks',
  'format-float-left': 'Apung Kiri Teks',
  'format-float-none': 'Tanpa Apung Teks',
  'format-float-right': 'Apung Kanan Teks',
  'format-font': 'Jenis Huruf Teks',
  'format-font-size-decrease': 'Kecilkan Huruf Teks',
  'format-font-size-increase': 'Besarkan Huruf Teks',
  'format-header-1': 'Judul 1 Teks',
  'format-header-2': 'Judul 2 Teks',
  'format-header-3': 'Judul 3 Teks',
  'format-header-4': 'Judul 4 Teks',
  'format-header-5': 'Judul 5 Teks',
  'format-header-6': 'Judul 6 Teks',
  'format-header-decrease': 'Kecilkan Judul Teks',
  'format-header-increase': 'Besarkan Judul Teks',
  'format-header-pound': 'Judul Tagar Teks',
  'format-horizontal-align-center': 'Rata Tengah Datar Teks',
  'format-horizontal-align-left': 'Rata Kiri Datar Teks',
  'format-horizontal-align-right': 'Rata Kanan Datar Teks',
  'format-indent-decrease': 'Kurangi Inden Teks',
  'format-indent-increase': 'Tambah Inden Teks',
  'format-italic': 'Teks Miring',
  'format-line-spacing': 'Spasi Baris Teks',
  'format-line-style': 'Gaya Garis Teks',
  'format-line-weight': 'Tebal Garis Teks',
  'format-list-bulleted': 'Daftar Bulat Teks',
  'format-list-bulleted-type': 'Jenis Daftar Bulat Teks',
  'format-list-checkbox': 'Daftar Kotak Teks',
  'format-list-checks': 'Daftar Centang Teks',
  'format-list-numbered': 'Daftar Angka Teks',
  'format-list-numbered-rtl': 'Daftar Angka Kanan Teks',
  'format-page-break': 'Pemisah Halaman Teks',
  'format-paint': 'Format Kuas Teks',
  'format-paragraph': 'Paragraf Teks',
  'format-quote-close': 'Tutup Kutipan Teks',
  'format-quote-open': 'Buka Kutipan Teks',
  'format-rotate-90': 'Putar 90 Derajat Teks',
  'format-section': 'Bagian Teks',
  'format-size': 'Ukuran Teks',
  'format-strikethrough': 'Teks Coret',
  'format-strikethrough-variant': 'Teks Coret Lain',
  'format-subscript': 'Teks Bawah',
  'format-superscript': 'Teks Atas',
  'format-text': 'Format Teks Utama',
  'format-text-wrapping-clip': 'Potong Bungkus Teks',
  'format-text-wrapping-overflow': 'Luber Bungkus Teks',
  'format-text-wrapping-wrap': 'Bungkus Teks Otomatis',
  'format-textbox': 'Kotak Teks Input',
  'format-textdirection-l-to-r': 'Teks Kiri ke Kanan',
  'format-textdirection-r-to-l': 'Teks Kanan ke Kanan',
  'format-title': 'Judul Utama Teks',
  'format-underline': 'Teks Garis Bawah',
  'format-vertical-align-bottom': 'Rata Bawah Tegak Teks',
  'format-vertical-align-center': 'Rata Tengah Tegak Teks',
  'format-vertical-align-top': 'Rata Atas Tegak Teks',
  'format-wrap-inline': 'Bungkus Dalam Teks',
  forum: 'Forum Diskusi',
  'forum-outline': 'Garis Forum',
  forward: 'Teruskan',
  forwardburger: 'Menu Teruskan',
  fountain: 'Air Mancur',
  'fountain-pen': 'Pena Tinta',
  'fountain-pen-tip': 'Ujung Pena',
  freebsd: 'Freebsd',
  'fridge-bottom': 'Kulkas Bawah',
  'fridge-top': 'Kulkas Atas',
  fuel: 'Bahan Bakar',
  fullscreen: 'Layar Penuh',
  'fullscreen-exit': 'Keluar Layar Penuh',
  function: 'Fungsi Matematika',
  'function-variant': 'Fungsi Lain',
  fuse: 'Sekring Listrik',
  'fuse-blade': 'Sekring Pisau',
  gamepad: 'Kontrol Game',
  'gamepad-circle': 'Kontrol Game Bulat',
  'gamepad-circle-down': 'Kontrol Game Bawah',
  'gamepad-circle-left': 'Kontrol Game Kiri',
  'gamepad-circle-outline': 'Garis Kontrol Game',
  'gamepad-circle-right': 'Kontrol Game Kanan',
  'gamepad-circle-up': 'Kontrol Game Atas',
  'gamepad-down': 'Kontrol Bawah',
  'gamepad-left': 'Kontrol Kiri',
  'gamepad-right': 'Kontrol Kanan',
  'gamepad-up': 'Kontrol Atas',
  'gamepad-variant-outline': 'Garis Stik Game',
  gamma: 'Simbol Gamma',
  'gantry-crane': 'Kren Gantry',
  garage: 'Garasi Mobil',
  'garage-alert': 'Garasi Bahaya',
  'garage-open': 'Garasi Terbuka',
  'gas-cylinder-outline': 'Garis Tabung Gas',
  'gas-station-variant': 'Pom Bensin Lain',
  gate: 'Pagar Gerbang',
  'gate-and': 'Gerbang Dan',
  'gate-nand': 'Gerbang Nand',
  'gate-nor': 'Gerbang Nor',
  'gate-not': 'Gerbang Tidak',
  'gate-or': 'Gerbang Atau',
  'gate-xnor': 'Gerbang Xnor',
  'gate-xor': 'Gerbang Xor',
  gauge: 'Alat Ukur',
  'gauge-empty': 'Ukur Kosong',
  'gauge-full': 'Ukur Penuh',
  'gauge-low': 'Ukur Rendah',
  'gavel-outline': 'Garis Palu Sidang',
  'gender-female': 'Perempuan',
  'gender-male': 'Laki-laki',
  'gender-male-female': 'Laki Perempuan',
  'gender-transgender': 'Transgender',
  gentoo: 'Gentoo',
  gesture: 'Gerakan Tangan',
  'gesture-double-tap': 'Ketuk Ganda',
  'gesture-swipe-down': 'Geser Bawah',
  'gesture-swipe-horizontal': 'Geser Datar',
  'gesture-swipe-left': 'Geser Kiri',
  'gesture-swipe-right': 'Geser Kanan',
  'gesture-swipe-up': 'Geser Atas',
  'gesture-swipe-vertical': 'Geser Tegak',
  'gesture-tap': 'Ketuk Jari',
  'gesture-two-double-tap': 'Dua Jari Ketuk Ganda',
  'gesture-two-tap': 'Dua Jari Ketuk',
  ghost: 'Hantu Seram',
  'gift-outline': 'Bungkus Kado',
  git: 'Git Kode',
  'glass-cocktail': 'Gelas Cocktail',
  'glass-flute': 'Gelas Sampanye',
  'glass-stipple': 'Gelas Smoothies',
  'glass-wine-outline': 'Garis Gelas Wine',
  glassdoor: 'Pintu Kaca',
  'glasses-outline': 'Garis Kacamata',
  'globe-model': 'Model Bola Dunia',
  gmail: 'Email Google',
  gnome: 'Gnome',
  'go-kart': 'Main Gokart',
  'go-kart-track': 'Lintasan Gokart',
  gog: 'Gog Game',
  'gold-outline': 'Garis Emas',
  golf: 'Main Golf',
  'golf-tee': 'Tee Golf',
  gondola: 'Perahu Gondola',
  google: 'Google Mesin Cari',
  'google-ads': 'Iklan Google',
  'google-analytics': 'Analitik Google',
  'google-assistant': 'Asisten Google',
  'google-cardboard': 'Google Cardboard',
  'google-chrome': 'Chrome Browser',
  'google-circles': 'Lingkaran Google',
  'google-circles-communities': 'Komunitas Google',
  'google-circles-extended': 'Google Perluas',
  'google-circles-group': 'Grup Google',
  'google-controller': 'Kontrol Google',
  'google-controller-off': 'Kontrol Google Mati',
  'google-drive': 'Drive Google',
  'google-earth': 'Bumi Google',
  'google-fit': 'Fit Google',
  'google-glass': 'Kacamata Google',
  'google-keep': 'Catatan Keep',
  'google-maps': 'Peta Google',
  'google-nearby': 'Sekitar Google',
  'google-pages': 'Halaman Google',
  'google-photos': 'Foto Google',
  'google-play': 'Toko Play',
  'google-plus': 'Google Plus Lama',
  'google-plus-box': 'Kotak Google Plus',
  'google-spreadsheet': 'Tabel Google',
  'google-translate': 'Terjemah Google',
  gpu: 'Kartu Grafis',
  gradient: 'Gradasi Warna',
  grain: 'Butiran',
  graph: 'Grafik Data',
  graphql: 'Graphql Kode',
  'grave-stone': 'Batu Nisan',
  'grease-pencil': 'Pensil Lemak',
  'greater-than': 'Lebih Besar Dari',
  'greater-than-or-equal': 'Lebih Besar Sama Dengan',
  grid: 'Kotak-kotak Grid',
  'grid-large': 'Grid Besar',
  'grid-off': 'Grid Mati',
  group: 'Grup Orang',
  'guitar-acoustic': 'Gitar Akustik',
  'guitar-electric': 'Gitar Listrik',
  'guitar-pick': 'Pemetik Gitar',
  'guitar-pick-outline': 'Garis Pemetik Gitar',
  'guy-fawkes-mask': 'Topeng Anonim',
  hail: 'Hujan Es',
  halloween: 'Labu Halloween',
  'hamburger-off': 'Tanpa Burger',
  hand: 'Tangan Manusia',
  'hand-pointing-down': 'Tunjuk Bawah',
  'hand-pointing-left': 'Tunjuk Kiri',
  'hand-pointing-right': 'Tunjuk Kanan',
  'hand-pointing-up': 'Tunjuk Atas',
  'hand-right': 'Tangan Kanan',
  'hand-saw': 'Gergaji Tangan',
  'hand-wash': 'Cuci Tangan Sabun',
  'hand-water': 'Tangan Air',
  handball: 'Bola Tangan',
  handcuffs: 'Borgol Polisi',
  'handshake-outline': 'Garis Jabat Tangan',
  'hanger-outline': 'Garis Gantungan',
  harddisk: 'Harddisk Data',
  'hat-fedora': 'Topi Fedora',
  'hazard-lights': 'Lampu Darurat',
  hdr: 'Foto HDR',
  'hdr-off': 'HDR Mati',
  'head-flash': 'Kepala Kilat',
  'head-heart': 'Kepala Hati',
  'head-minus': 'Kepala Kurang',
  'head-plus': 'Kepala Tambah',
  'head-question': 'Kepala Tanya',
  'headphones-bluetooth': 'Headset Bluetooth',
  'headphones-box': 'Kotak Headset',
  'headphones-off': 'Headset Mati',
  'headphones-settings': 'Setelan Headset',
  headset: 'Headset Mikrofon',
  'headset-dock': 'Dudukan Headset',
  'headset-off': 'Headset Mati Lain',
  'heart-broken': 'Patah Hati',
  'heart-circle': 'Hati Bulat',
  'heart-circle-outline': 'Garis Hati Bulat',
  'heart-half': 'Setengah Hati',
  'heart-half-full': 'Hati Setengah Isi',
  'heart-half-outline': 'Garis Setengah Hati',
  'heart-minus-outline': 'Garis Kurang Hati',
  'heart-multiple': 'Banyak Hati',
  'heart-off': 'Hati Mati',
  'heart-outline': 'Garis Hati',
  'heart-plus-outline': 'Garis Tambah Hati',
  'heart-pulse-outline': 'Garis Detak Jantung',
  helicopter: 'Helikopter Terbang',
  help: 'Bantuan Tanya',
  'help-box': 'Kotak Bantuan',
  'help-circle-outline': 'Garis Tanya Bulat',
  'help-network': 'Bantuan Jaringan',
  'help-rhombus': 'Bantuan Belah Ketupat',
  hexagon: 'Segi Enam',
  'hexagon-multiple': 'Banyak Segi Enam',
  'hexagon-outline': 'Garis Segi Enam',
  'hexagon-slice-1': 'Irisan Segi Enam 1',
  'hexagon-slice-2': 'Irisan Segi Enam 2',
  'hexagon-slice-3': 'Irisan Segi Enam 3',
  'hexagon-slice-4': 'Irisan Segi Enam 4',
  'hexagon-slice-5': 'Irisan Segi Enam 5',
  'hexagon-slice-6': 'Irisan Segi Enam 6',
  highway: 'Jalan Tol Panjang',
  hiking: 'Mendaki Gunung',
  hinduism: 'Simbol Hindu',
  'history-outline': 'Garis Riwayat',
  'hockey-puck': 'Puck Hoki',
  'hockey-sticks': 'Tongkat Hoki',
  hololens: 'Holo Lens',
  'home-account': 'Akun Rumah',
  'home-alert': 'Rumah Bahaya',
  'home-assistant': 'Asisten Rumah',
  'home-automation': 'Otomasi Rumah',
  'home-circle': 'Rumah Bulat',
  'home-city-outline': 'Garis Gedung Kota',
  'home-currency-usd': 'Rumah Dolar',
  'home-edit': 'Edit Rumah',
  'home-export-outline': 'Garis Ekspor Rumah',
  'home-flood': 'Rumah Banjir',
  'home-floor-0': 'Rumah Lantai Dasar',
  'home-floor-1': 'Rumah Lantai 1',
  'home-floor-2': 'Rumah Lantai 2',
  'home-floor-3': 'Rumah Lantai 3',
  'home-floor-a': 'Rumah Lantai A',
  'home-floor-b': 'Rumah Lantai B',
  'home-floor-g': 'Rumah Lantai G',
  'home-floor-l': 'Rumah Lantai L',
  'home-group': 'Grup Rumah',
  'home-heart': 'Rumah Sayang',
  'home-import-outline': 'Garis Impor Rumah',
  'home-lock': 'Rumah Kunci',
  'home-lock-open': 'Rumah Buka Kunci',
  'home-map-marker': 'Lokasi Rumah Peta',
  'home-minus': 'Kurang Rumah',
  'home-modern': 'Rumah Modern',
  'home-outline': 'Garis Rumah',
  'home-plus-outline': 'Garis Tambah Rumah',
  'home-remove': 'Hapus Rumah',
  'home-roof': 'Atap Rumah',
  'home-search': 'Cari Rumah',
  'home-thermometer': 'Suhu Rumah',
  'home-variant-outline': 'Garis Rumah Lain',
  hook: 'Kait Besi',
  hop: 'Lompat Hops',
  horseshoe: 'Tapal Kuda',
  hospital: 'Rumah Sakit Besar',
  'hospital-marker': 'Lokasi Rumah Sakit',
  'hot-tub': 'Bak Air Panas',
  hotel: 'Menginap di Hotel',
  houzz: 'Houzz Dekor',
  hubspot: 'Hubspot',
  hulu: 'Hulu Streaming',
  human: 'Manusia Berdiri',
  'human-baby-changing': 'Ganti Popok',
  'human-child': 'Anak Kecil',
  'human-edit': 'Edit Manusia',
  'human-female': 'Wanita Berdiri',
  'human-female-boy': 'Ibu dan Anak Laki',
  'human-female-child': 'Ibu dan Anak',
  'human-female-female': 'Dua Wanita',
  'human-female-girl': 'Ibu dan Anak Perempuan',
  'human-greeting': 'Menyapa Orang',
  'human-handsdown': 'Tangan di Bawah',
  'human-handsup': 'Tangan di Atas',
  'human-male': 'Pria Berdiri',
  'human-male-boy': 'Ayah dan Anak Laki',
  'human-male-child': 'Ayah dan Anak',
  'human-male-female': 'Pria dan Wanita',
  'human-male-girl': 'Ayah dan Anak Perempuan',
  'human-male-male': 'Dua Pria',
  'human-pregnant': 'Wanita Hamil',
  'human-wheelchair': 'Orang di Kursi Roda',
  humidifier: 'Pelembab Udara',
  'hydraulic-oil-level': 'Level Oli Hidrolik',
  'hydraulic-oil-temperature': 'Suhu Oli Hidrolik',
  'hydro-power': 'Tenaga Air',
  'ice-cream-off': 'Tanpa Es Krim',
  'id-card': 'Kartu Identitas KTP',
  identifier: 'Pengenal',
  'image-album': 'Album Foto',
  'image-area': 'Area Gambar',
  'image-area-close': 'Tutup Area Gambar',
  'image-broken': 'Gambar Rusak',
  'image-broken-variant': 'Gambar Rusak Lain',
  'image-filter-black-white': 'Filter Hitam Putih',
  'image-filter-center-focus': 'Fokus Tengah Gambar',
  'image-filter-drama': 'Filter Drama',
  'image-filter-frames': 'Bingkai Foto',
  'image-filter-hdr': 'Filter HDR',
  'image-filter-none': 'Tanpa Filter Foto',
  'image-filter-tilt-shift': 'Filter Miring Gambar',
  'image-filter-vintage': 'Filter Jadul Foto',
  'image-frame': 'Pigura Foto',
  'image-move': 'Pindah Gambar',
  'image-multiple': 'Banyak Foto Galeri',
  'image-off': 'Foto Mati',
  'image-outline': 'Garis Foto',
  'image-plus': 'Tambah Foto Baru',
  'image-search': 'Cari Foto',
  'image-size-select-actual': 'Ukuran Foto Asli',
  'image-size-select-large': 'Ukuran Foto Besar',
  'image-size-select-small': 'Ukuran Foto Kecil',
  import: 'Terima Masuk',
  inbox: 'Kotak Masuk Surat',
  'inbox-arrow-down': 'Surat Masuk Bawah',
  'inbox-arrow-up': 'Surat Keluar Atas',
  'inbox-multiple': 'Banyak Kotak Masuk',
  incognito: 'Mode Penyamaran',
  infinity: 'Tak Terhingga',
  'information-outline': 'Garis Info',
  'information-variant': 'Info Lainnya',
  instagram: 'Instagram Sosial',
  instapaper: 'Instapaper',
  'internet-explorer': 'Internet Explorer Lama',
  'invert-colors': 'Balik Warna',
  'invert-colors-off': 'Warna Normal',
  ip: 'Alamat IP',
  'ip-network': 'IP Jaringan',
  ipod: 'Pemutar Lagu Ipod',
  islam: 'Simbol Islam',
  itunes: 'Itunes Musik',
  jeepney: 'Angkot Jeepney',
  jira: 'Jira Tugas',
  jsfiddle: 'Jsfiddle',
  json: 'Format JSON',
  judaism: 'Simbol Yahudi',
  kabaddi: 'Olahraga Kabaddi',
  karate: 'Bela Diri Karate',
  keg: 'Tong Bir',
  'kettle-outline': 'Garis Teko',
  'key-arrow-right': 'Kunci Kanan',
  'key-change': 'Ganti Kunci',
  'key-minus': 'Kurang Kunci',
  'key-outline': 'Garis Kunci',
  'key-plus': 'Tambah Kunci',
  'key-remove': 'Hapus Kunci',
  'key-variant': 'Kunci Lain',
  'keyboard-backspace': 'Keyboard Hapus',
  'keyboard-caps': 'Keyboard Huruf Besar',
  'keyboard-close': 'Keyboard Tutup',
  'keyboard-off': 'Keyboard Mati',
  'keyboard-outline': 'Garis Papan Ketik',
  'keyboard-return': 'Keyboard Enter',
  'keyboard-settings': 'Setelan Keyboard',
  'keyboard-tab': 'Keyboard Tab',
  'keyboard-variant': 'Keyboard Lain',
  khanda: 'Simbol Khanda',
  kickstarter: 'Kickstarter',
  knife: 'Pisau Dapur',
  'knife-military': 'Pisau Militer',
  kodi: 'Kodi Media',
  'label-multiple': 'Banyak Label',
  'label-outline': 'Garis Label',
  'label-variant': 'Label Lain',
  ladybug: 'Kepik Merah',
  lambda: 'Simbol Lambda',
  lamp: 'Lampu Tidur',
  lan: 'Kabel Lan Jaringan',
  'lan-check': 'Lan Aman',
  'lan-connect': 'Lan Terhubung',
  'lan-disconnect': 'Lan Terputus',
  'lan-pending': 'Lan Menunggu',
  'language-c': 'Bahasa C',
  'language-cpp': 'Bahasa C++',
  'language-csharp': 'Bahasa C#',
  'language-css3': 'Bahasa CSS',
  'language-go': 'Bahasa Go',
  'language-haskell': 'Bahasa Haskell',
  'language-html5': 'Bahasa HTML',
  'language-java': 'Bahasa Java',
  'language-javascript': 'Bahasa Javascript',
  'language-lua': 'Bahasa Lua',
  'language-php': 'Bahasa PHP',
  'language-python': 'Bahasa Python',
  'language-python-text': 'Teks Python',
  'language-r': 'Bahasa R',
  'language-ruby-on-rails': 'Bahasa Ruby',
  'language-swift': 'Bahasa Swift',
  'language-typescript': 'Bahasa Typescript',
  'laptop-chromebook': 'Chromebook',
  'laptop-mac': 'Macbook Pro',
  'laptop-off': 'Laptop Mati',
  'laptop-windows': 'Laptop Windows',
  lastfm: 'Lastfm',
  launch: 'Luncurkan',
  'lava-lamp': 'Lampu Lava',
  'layers-off': 'Lapisan Mati',
  'layers-outline': 'Garis Lapisan',
  'lead-pencil': 'Pensil Kayu',
  leaf: 'Daun Hijau',
  'led-off': 'Lampu LED Mati',
  'led-on': 'Lampu LED Nyala',
  'led-outline': 'Garis Lampu LED',
  'led-variant-off': 'Varian LED Mati',
  'led-variant-on': 'Varian LED Nyala',
  'led-variant-outline': 'Garis Varian LED',
  library: 'Perpustakaan Buku',
  'library-books': 'Koleksi Buku',
  'library-movie': 'Koleksi Film',
  'library-music': 'Koleksi Musik',
  'library-plus': 'Tambah Koleksi',
  'library-video': 'Koleksi Video',
  lifebuoy: 'Pelampung Penyelamat',
  lightbulb: 'Bohlam Lampu',
  'lightbulb-off': 'Bohlam Mati',
  'lightbulb-on': 'Bohlam Nyala',
  'lightbulb-outline': 'Garis Bohlam',
  'link-off': 'Tautan Putus',
  'link-variant': 'Tautan Lain',
  'link-variant-off': 'Tautan Lain Putus',
  linkedin: 'Linkedin Kerja',
  linux: 'Linux Pinguin',
  'linux-mint': 'Linux Mint',
  litecoin: 'Litecoin Koin',
  loading: 'Lagi Loading',
  'lock-alert': 'Kunci Bahaya',
  'lock-clock': 'Kunci Waktu',
  'lock-open': 'Kunci Terbuka',
  'lock-open-outline': 'Garis Kunci Terbuka',
  'lock-outline': 'Garis Gembok',
  'lock-pattern': 'Pola Kunci',
  'lock-plus': 'Tambah Kunci Gembok',
  'lock-question': 'Kunci Tanya',
  'lock-reset': 'Reset Kunci',
  'lock-smart': 'Kunci Pintar',
  locker: 'Loker Lemari',
  'locker-multiple': 'Banyak Loker',
  login: 'Masuk Akun',
  'login-variant': 'Masuk Akun Lain',
  logout: 'Keluar Akun',
  'logout-variant': 'Keluar Akun Lain',
  looks: 'Pelangi Indah',
  loupe: 'Kaca Pembesar Zoom',
  lumosity: 'Lumosity',
  magnet: 'Magnet Besi',
  'magnet-on': 'Magnet Nyala',
  'magnify-minus': 'Zoom Kecil',
  'magnify-plus': 'Zoom Besar',
  mail: 'Surat Pos',
  'mail-ru': 'Mail Ru',
  mailbox: 'Kotak Surat Depan',
  'map-legend': 'Legenda Peta',
  'map-marker-check': 'Lokasi Benar',
  'map-marker-circle': 'Lokasi Bulat',
  'map-marker-distance': 'Jarak Lokasi',
  'map-marker-minus': 'Hapus Lokasi',
  'map-marker-multiple': 'Banyak Lokasi',
  'map-marker-off': 'Lokasi Mati',
  'map-marker-outline': 'Garis Lokasi Peta',
  'map-marker-plus': 'Tambah Lokasi Peta',
  'map-marker-radius-outline': 'Garis Radius Lokasi',
  'map-outline': 'Garis Peta',
  'map-search': 'Cari di Peta',
  margin: 'Margin Halaman',
  markdown: 'Format Markdown',
  marker: 'Spidol Penanda',
  'marker-check': 'Spidol Benar',
  mastodon: 'Mastodon Sosial',
  'material-design': 'Material Design',
  'material-ui': 'Material UI',
  'math-compass': 'Jangka Matematika',
  'math-cos': 'Cos Matematika',
  'math-sin': 'Sin Matematika',
  'math-tan': 'Tan Matematika',
  matrix: 'Matrix',
  'medical-cotton-swab': 'Korek Kuping Kapas',
  meditation: 'Meditasi Tenang',
  memory: 'Memori RAM',
  menu: 'Menu Utama',
  'menu-down': 'Menu Bawah',
  'menu-left': 'Menu Kiri',
  'menu-open': 'Menu Buka',
  'menu-right': 'Menu Kanan',
  'menu-up': 'Menu Atas',
  message: 'Pesan Obrolan',
  'message-alert': 'Pesan Bahaya',
  'message-draw': 'Tulis Pesan',
  'message-image': 'Pesan Foto',
  'message-outline': 'Garis Pesan',
  'message-plus': 'Tambah Pesan',
  'message-processing': 'Pesan Diproses',
  'message-reply': 'Balas Pesan Obrolan',
  'message-reply-text': 'Balas Pesan Teks',
  'message-settings': 'Setelan Pesan',
  'message-text': 'Pesan Teks Saja',
  'message-video': 'Pesan Video',
  meteor: 'Meteor Jatuh',
  metronome: 'Metronome Musik',
  'micro-sd': 'Kartu Memori Kecil',
  microphone: 'Mic Suara',
  'microphone-off': 'Mic Mati',
  'microphone-outline': 'Garis Mic',
  'microphone-settings': 'Setelan Mic',
  'microphone-variant': 'Mic Lain',
  'microphone-variant-off': 'Mic Lain Mati',
  microscope: 'Mikroskop Lab',
  microsoft: 'Microsoft',
  'microsoft-dynamics': 'Microsoft Dynamics',
  'microsoft-edge': 'Browser Microsoft',
  'microsoft-excel': 'Excel Microsoft',
  'microsoft-office': 'Office Microsoft',
  'microsoft-outlook': 'Outlook Microsoft',
  'microsoft-powerpoint': 'Powerpoint Microsoft',
  'microsoft-sharepoint': 'Sharepoint Microsoft',
  'microsoft-teams': 'Teams Microsoft',
  'microsoft-visual-studio': 'Visual Studio',
  'microsoft-visual-studio-code': 'VS Code',
  'microsoft-windows': 'Windows Microsoft',
  'microsoft-word': 'Word Microsoft',
  'microsoft-xbox': 'Xbox Game',
  'microwave-empty': 'Microwave Kosong',
  'middle-finger': 'Jari Tengah Ejek',
  midi: 'Midi Musik',
  mine: 'Tambang Tambang',
  minecraft: 'Game Minecraft',
  'mini-sd': 'Kartu Memori Mini',
  minidisc: 'Mini Disc Piringan',
  minus: 'Kurang Satu',
  'minus-box': 'Kotak Kurang',
  'minus-circle-outline': 'Garis Kurang Bulat',
  mirror: 'Cermin Kaca',
  'mixed-martial-arts': 'Olahraga MMA',
  'mixed-reality': 'Mixed Reality',
  molecule: 'Molekul Kimia',
  'monitor-cellphone': 'Layar HP',
  'monitor-cellphone-star': 'Layar HP Bintang',
  'monitor-clean': 'Layar Bersih',
  'monitor-dashboard': 'Dashboard Layar',
  'monitor-edit': 'Edit Layar',
  'monitor-lock': 'Layar Kunci',
  'monitor-multiple': 'Banyak Layar',
  'monitor-off': 'Layar Mati',
  'monitor-screenshot': 'Tangkap Layar Monitor',
  'monitor-star': 'Layar Bintang',
  'moon-first-quarter': 'Bulan Seperempat Pertama',
  'moon-full': 'Bulan Purnama',
  'moon-last-quarter': 'Bulan Seperempat Terakhir',
  'moon-new': 'Bulan Baru',
  'moon-waning-crescent': 'Bulan Sabit Tua',
  'moon-waning-gibbous': 'Bulan Cembung Tua',
  'moon-waxing-crescent': 'Bulan Sabit Muda',
  'moon-waxing-gibbous': 'Bulan Cembung Muda',
  more: 'Lainnya',
  'mother-nurse': 'Suster Perawat',
  'motion-sensor': 'Sensor Gerak',
  'motorbike-outline': 'Garis Motor',
  'mouse-bluetooth': 'Mouse Bluetooth',
  'mouse-off': 'Mouse Mati',
  'mouse-variant': 'Mouse Lain',
  'mouse-variant-off': 'Mouse Lain Mati',
  'move-resize': 'Pindah Ukuran',
  'move-resize-variant': 'Pindah Ukuran Lain',
  'movie-edit': 'Edit Film',
  'movie-open': 'Film Dibuka',
  'movie-outline': 'Garis Film',
  'movie-roll': 'Gulungan Film Lama',
  muffin: 'Kue Muffin',
  multiplication: 'Perkalian Angka',
  'multiplication-box': 'Kotak Kali',
  mushroom: 'Jamur Hutan',
  'mushroom-outline': 'Garis Jamur',
  'music-box': 'Kotak Musik',
  'music-box-outline': 'Garis Kotak Musik',
  'music-circle': 'Musik Bulat',
  'music-note': 'Not Balok Musik',
  'music-note-bluetooth': 'Not Balok Bluetooth',
  'music-note-bluetooth-off': 'Not Balok Bluetooth Mati',
  'music-note-eighth': 'Not Balok Perdelapan',
  'music-note-half': 'Not Balok Setengah',
  'music-note-off': 'Not Balok Mati',
  'music-note-plus': 'Tambah Not Balok',
  'music-note-quarter': 'Not Balok Perempat',
  'music-note-sixteenth': 'Not Balok Perenambelas',
  'music-note-whole': 'Not Balok Utuh',
  'music-off': 'Musik Mati',
  nature: 'Alam Semesta',
  'nature-people': 'Alam dan Orang',
  'navigation-outline': 'Garis Navigasi',
  'near-me': 'Dekat Saya',
  needle: 'Jarum Jahit',
  network: 'Jaringan Koneksi',
  'network-strength-1': 'Sinyal Lemah 1',
  'network-strength-2': 'Sinyal Lemah 2',
  'network-strength-3': 'Sinyal Kuat 3',
  'network-strength-4': 'Sinyal Sangat Kuat 4',
  'network-strength-off': 'Sinyal Mati',
  'network-strength-outline': 'Garis Sinyal',
  'new-box': 'Kotak Baru',
  newspaper: 'Koran Berita',
  nfc: 'NFC HP',
  'nfc-tap': 'Ketuk NFC',
  'nfc-variant': 'NFC Lain',
  ninja: 'Ninja Jepang',
  'nintendo-switch': 'Nintendo Switch Game',
  nodejs: 'Node JS',
  'not-equal': 'Tidak Sama Dengan',
  'not-equal-variant': 'Tidak Sama Dengan Lain',
  note: 'Catatan Kecil',
  'note-multiple': 'Banyak Catatan',
  'note-outline': 'Garis Catatan',
  'note-plus': 'Tambah Catatan',
  'note-text': 'Catatan Teks',
  'notification-clear-all': 'Hapus Semua Notif',
  npm: 'Paket NPM',
  nuke: 'Nuklir Bahaya',
  null: 'Kosong Null',
  numeric: 'Angka Numerik',
  'numeric-0': 'Angka 0',
  'numeric-1': 'Angka 1',
  'numeric-2': 'Angka 2',
  'numeric-3': 'Angka 3',
  'numeric-4': 'Angka 4',
  'numeric-5': 'Angka 5',
  'numeric-6': 'Angka 6',
  'numeric-7': 'Angka 7',
  'numeric-8': 'Angka 8',
  'numeric-9': 'Angka 9',
  'numeric-0-box': 'Kotak Angka 0',
  'numeric-1-box': 'Kotak Angka 1',
  nut: 'Mur Besi',
  nutrition: 'Nutrisi Makanan',
  oar: 'Dayung Perahu',
  octagon: 'Segi Delapan',
  'octagon-outline': 'Garis Segi Delapan',
  octagram: 'Bintang Segi Delapan',
  odnoklassniki: 'Odnoklassniki',
  'office-building': 'Gedung Kantor Besar',
  oil: 'Oli Mesin',
  'oil-temperature': 'Suhu Oli',
  omega: 'Simbol Omega',
  'one-up': 'Nyawa Tambahan 1UP',
  onedrive: 'Onedrive Microsoft',
  opacity: 'Transparansi',
  'open-in-app': 'Buka di Aplikasi',
  'open-in-new': 'Buka di Tab Baru',
  openid: 'Openid',
  opera: 'Browser Opera',
  orbit: 'Orbit Planet',
  ornament: 'Hiasan',
  'ornament-variant': 'Hiasan Lain',
  owl: 'Burung Hantu',
  'package-down': 'Paket Turun',
  'package-up': 'Paket Naik',
  'package-variant': 'Paket Lain',
  'package-variant-closed': 'Paket Tertutup',
  'page-first': 'Halaman Pertama',
  'page-last': 'Halaman Terakhir',
  'page-layout-body': 'Tata Letak Badan',
  'page-layout-footer': 'Tata Letak Kaki',
  'page-layout-header': 'Tata Letak Kepala',
  'page-layout-sidebar-left': 'Sidebar Kiri',
  'page-layout-sidebar-right': 'Sidebar Kanan',
  'page-next': 'Halaman Berikutnya',
  'page-previous': 'Halaman Sebelumnya',
  'palette-outline': 'Garis Palet Warna',
  'palette-swatch': 'Contoh Warna',
  'pan-bottom-left': 'Geser Kiri Bawah',
  'pan-bottom-right': 'Geser Kanan Bawah',
  'pan-down': 'Geser Bawah',
  'pan-horizontal': 'Geser Datar',
  'pan-left': 'Geser Kiri',
  'pan-right': 'Geser Kanan',
  'pan-top-left': 'Geser Kiri Atas',
  'pan-top-right': 'Geser Kanan Atas',
  'pan-up': 'Geser Atas',
  'pan-vertical': 'Geser Tegak',
  panda: 'Beruang Panda',
  pandora: 'Pandora Musik',
  'paper-cut-vertical': 'Potong Kertas Tegak',
  'paperclip-outline': 'Garis Klip Kertas',
  paragliding: 'Olahraga Paralayang',
  'parking-outline': 'Garis Parkir',
  'passport-outline': 'Garis Paspor',
  patreon: 'Patreon Kreator',
  pause: 'Jeda',
  'pause-circle': 'Jeda Bulat',
  'pause-octagon': 'Jeda Delapan',
  'paw-off': 'Tanpa Jejak Hewan',
  'pdf-box': 'Kotak PDF',
  peace: 'Simbol Damai',
  pen: 'Pulpen Tulis',
  'pencil-box': 'Kotak Pensil',
  'pencil-lock': 'Pensil Kunci',
  'pencil-off': 'Pensil Mati',
  'pencil-outline': 'Garis Pensil',
  'percent-outline': 'Garis Persen',
  'periodic-table': 'Tabel Periodik Kimia',
  pharmacy: 'Apotek Obat',
  'phone-bluetooth': 'Telepon Bluetooth',
  'phone-forward': 'Telepon Teruskan',
  'phone-hangup': 'Telepon Tutup',
  'phone-in-talk': 'Telepon Sedang Bicara',
  'phone-incoming': 'Telepon Masuk Lain',
  'phone-lock': 'Telepon Kunci',
  'phone-log': 'Log Telepon',
  'phone-minus': 'Hapus Kontak Telp',
  'phone-missed': 'Telepon Tak Terjawab Lain',
  'phone-off': 'Telepon Mati',
  'phone-outgoing': 'Telepon Keluar Lain',
  'phone-outline': 'Garis Telepon',
  'phone-paused': 'Telepon Jeda',
  'phone-plus': 'Tambah Kontak Telp',
  'phone-settings': 'Setelan Telepon',
  'phone-voip': 'Telepon Internet',
  pi: 'Simbol Pi Matematika',
  piano: 'Alat Musik Piano',
  pickaxe: 'Beliung Tambang',
  'pierce-anywhere': 'Tembus Mana Saja',
  'piggy-bank-outline': 'Garis Celengan',
  'pill-off': 'Tanpa Obat',
  'pine-tree': 'Pohon Pinus',
  'pine-tree-box': 'Kotak Pohon Pinus',
  pinterest: 'Pinterest Gambar',
  pipe: 'Pipa Air',
  'pipe-disconnected': 'Pipa Terputus',
  'pipe-leak': 'Pipa Bocor',
  pistol: 'Senjata Pistol',
  'pizza-outline': 'Garis Pizza',
  play: 'Putar',
  'play-box': 'Kotak Putar',
  'play-circle': 'Putar Bulat',
  'play-network': 'Putar Jaringan',
  'play-pause': 'Putar Jeda Gabung',
  'play-protected-content': 'Putar Konten Dilindungi',
  'playlist-check': 'Playlist Selesai',
  'playlist-edit': 'Edit Playlist',
  'playlist-minus': 'Hapus dari Playlist',
  'playlist-music': 'Daftar Lagu',
  'playlist-music-outline': 'Garis Daftar Lagu',
  'playlist-play': 'Putar Playlist',
  'playlist-plus': 'Tambah ke Playlist',
  'playlist-remove': 'Hapus Playlist',
  plex: 'Plex Media',
  plus: 'Tambah Satu Lain',
  'plus-box': 'Kotak Tambah',
  'plus-circle-multiple': 'Banyak Tambah Bulat',
  'plus-network': 'Tambah Jaringan',
  'plus-outline': 'Garis Tambah',
  'poker-chip': 'Chip Poker',
  'pool-outline': 'Garis Kolam Renang',
  'popcorn-outline': 'Garis Berondong Jagung',
  'postage-stamp': 'Perangko Surat',
  pot: 'Panci Masak',
  'pot-mix': 'Panci Aduk',
  'pot-outline': 'Garis Panci',
  'pot-steam': 'Panci Uap',
  pound: 'Tagar Hash',
  'pound-box': 'Kotak Tagar',
  power: 'Tombol Power',
  'power-cycle': 'Siklus Daya',
  'power-off': 'Mati Daya',
  'power-on': 'Nyala Daya',
  'power-plug-outline': 'Garis Colokan',
  'power-settings': 'Setelan Daya',
  'power-sleep': 'Mode Tidur',
  'power-socket': 'Stop Kontak',
  'power-socket-au': 'Stop Kontak AU',
  'power-socket-eu': 'Stop Kontak EU',
  'power-socket-uk': 'Stop Kontak UK',
  'power-socket-us': 'Stop Kontak US',
  'power-standby': 'Mode Standby',
  presentation: 'Layar Presentasi',
  'printer-3d': 'Printer 3D',
  'printer-alert': 'Printer Bahaya',
  'printer-settings': 'Setelan Printer',
  'professional-hexagon': 'Segi Enam Profesional',
  'progress-check': 'Progres Selesai',
  'progress-clock': 'Progres Waktu',
  'progress-download': 'Progres Unduh',
  'progress-upload': 'Progres Unggah',
  projector: 'Proyektor Layar',
  'projector-screen': 'Layar Proyektor',
  publish: 'Terbitkan',
  pulse: 'Garis Detak Jantung',
  pumpkin: 'Labu Kuning',
  purse: 'Dompet Kecil Wanita',
  'purse-outline': 'Garis Dompet Wanita',
  puzzle: 'Mainan Puzzle',
  'puzzle-outline': 'Garis Puzzle',
  qi: 'Cas Nirkabel Qi',
  qqchat: 'QQ Chat',
  'qrcode-edit': 'Edit QR Code',
  'qrcode-scan': 'Scan QR Code',
  quadcopter: 'Drone Quadcopter',
  'quality-high': 'Kualitas Tinggi',
  'quality-low': 'Kualitas Rendah',
  'quality-medium': 'Kualitas Sedang',
  quora: 'Quora Tanya Jawab',
  rabbit: 'Kelinci Lucu',
  'racing-helmet': 'Helm Balap Motor',
  radar: 'Radar Deteksi',
  radiator: 'Radiator Pemanas',
  'radiator-off': 'Radiator Mati',
  radio: 'Mendengar Radio',
  'radio-am': 'Radio AM',
  'radio-fm': 'Radio FM',
  'radio-handheld': 'HT Handy Talky',
  'radio-off': 'Radio Mati',
  'radio-tower': 'Menara Radio',
  radioactive: 'Radioaktif Bahaya',
  'radioactive-outline': 'Garis Radioaktif',
  'radiobox-blank': 'Pilihan Kosong',
  'radiobox-marked': 'Pilihan Terisi',
  'railroad-light': 'Lampu Kereta',
  'rare-view-gel': 'Gel Jarang',
  'raspberry-pi': 'Raspberry Pi',
  'ray-end': 'Ujung Sinar',
  'ray-end-arrow': 'Panah Ujung Sinar',
  'ray-start': 'Awal Sinar',
  'ray-start-arrow': 'Panah Awal Sinar',
  'ray-start-end': 'Awal Ujung Sinar',
  'ray-vertex': 'Titik Sudut Sinar',
  react: 'React JS Kode',
  read: 'Sudah Dibaca',
  'receipt-outline': 'Garis Struk Belanja',
  'receipt-plus': 'Tambah Struk',
  record: 'Rekam',
  'record-player': 'Pemutar Piringan Hitam',
  'record-rec': 'Rekam Video',
  recycle: 'Daur Ulang',
  reddit: 'Reddit Sosial',
  redo: 'Ulangi Lagi',
  'redo-variant': 'Ulangi Lagi Lain',
  'reflect-horizontal': 'Pantul Datar',
  'reflect-vertical': 'Pantul Tegak',
  'refresh-circle': 'Segarkan Bulat',
  regex: 'Regex Kode',
  'relative-scale': 'Skala Relatif',
  reload: 'Muat Ulang',
  reminder: 'Pengingat Transaksi',
  remote: 'Remote TV',
  'remote-desktop': 'Remote Komputer',
  'rename-box': 'Kotak Ubah Nama',
  'reorder-horizontal': 'Urutkan Datar',
  'reorder-vertical': 'Urutkan Tegak',
  repeat: 'Ulangi Terus',
  'repeat-once': 'Ulang Sekali',
  replay: 'Mainkan Lagi',
  reply: 'Balas Pesan',
  'reply-all': 'Balas Semua Pesan',
  reproduction: 'Reproduksi',
  resistor: 'Resistor Listrik',
  'resistor-nodes': 'Titik Resistor',
  resize: 'Ubah Ukuran',
  'resize-bottom-right': 'Ubah Ukuran Kanan Bawah',
  responsive: 'Responsif Layar',
  restart: 'Mulai Ulang',
  restore: 'Kembalikan Data',
  rewind: 'Putar Balik',
  'rewind-outline': 'Garis Putar Balik',
  rhombus: 'Belah Ketupat',
  'rhombus-outline': 'Garis Belah Ketupat',
  ribbon: 'Pita Hadiah',
  rice: 'Butiran Beras',
  'ring-outline': 'Garis Cincin',
  road: 'Jalan Raya Aspal',
  'road-variant': 'Jalan Raya Lain',
  robot: 'Robot Pintar',
  'robot-industrial': 'Robot Pabrik',
  'rocket-outline': 'Garis Roket',
  'room-service': 'Layanan Kamar Hotel',
  'rotate-3d': 'Putar 3D',
  'rotate-left': 'Putar ke Kiri',
  'rotate-right': 'Putar ke Kanan',
  'rounded-corner': 'Sudut Bulat',
  'router-wireless': 'Router Wifi',
  'router-wireless-settings': 'Setelan Router',
  routes: 'Rute Perjalanan',
  rowing: 'Olahraga Dayung',
  'rss-box': 'Kotak RSS',
  ruler: 'Penggaris Lurus',
  'run-fast': 'Lari Cepat',
  'safe-outline': 'Garis Brankas',
  sale: 'Diskon Sale',
  satellite: 'Satelit Angkasa',
  'satellite-variant': 'Satelit Lain',
  saucepan: 'Panci Kecil',
  'saw-blade': 'Mata Gergaji',
  scale: 'Timbangan Berat',
  'scale-balance-outline': 'Garis Timbangan Hukum',
  scanner: 'Alat Pemindai',
  'school-outline-variant': 'Garis Sekolah Lain',
  'scissors-cutting': 'Gunting Potong',
  'screen-rotation': 'Putar Layar',
  'screen-rotation-lock': 'Kunci Putar Layar',
  'screw-flat-top': 'Sekrup Datar',
  'screw-lag': 'Sekrup Lag',
  'screw-machine': 'Sekrup Mesin',
  'screw-round-top': 'Sekrup Bulat',
  screwdriver: 'Obeng Putar',
  sd: 'Kartu SD',
  seal: 'Segel Resmi',
  'search-web': 'Cari di Web',
  'seat-flat': 'Kursi Datar',
  'seat-flat-angled': 'Kursi Datar Miring',
  'seat-individual-suite': 'Kursi Suite',
  'seat-legroom-extra': 'Legroom Ekstra',
  'seat-legroom-normal': 'Legroom Normal',
  'seat-legroom-reduced': 'Legroom Sempit',
  'seat-outline': 'Garis Kursi',
  'seat-recline-extra': 'Kursi Reclining Ekstra',
  'seat-recline-normal': 'Kursi Reclining Normal',
  'security-network': 'Keamanan Jaringan',
  select: 'Pilih Sesuatu',
  'select-all': 'Pilih Semua Objek',
  'select-drag': 'Pilih Seret',
  'select-inverse': 'Pilih Terbalik',
  'select-off': 'Batal Pilih',
  selection: 'Seleksi',
  'selection-off': 'Seleksi Mati',
  'send-lock': 'Kirim Kunci',
  'send-outline': 'Garis Kirim',
  'serial-port': 'Port Serial',
  server: 'Server Data Komputer',
  'server-minus': 'Kurang Server',
  'server-network': 'Server Jaringan',
  'server-network-off': 'Server Jaringan Mati',
  'server-off': 'Server Mati',
  'server-plus': 'Tambah Server',
  'server-remove': 'Hapus Server',
  'server-security': 'Server Aman',
  shape: 'Bentuk Bentuk',
  'shape-outline': 'Garis Bentuk',
  'shape-plus': 'Tambah Bentuk',
  share: 'Bagi Transaksi',
  'share-variant-outline': 'Garis Bagikan',
  'shield-half-full': 'Perisai Setengah',
  'shield-outline': 'Garis Perisai',
  'ship-wheel': 'Setir Kapal',
  'shirt-crew-outline': 'Garis Kaos',
  'shoe-formal': 'Sepatu Pantofel',
  'shoe-heel': 'Sepatu Hak Tinggi',
  'shoe-print': 'Jejak Sepatu',
  'shopping-outline': 'Garis Belanja',
  'short-text': 'Teks Pendek',
  shovel: 'Sekop Tanah',
  shuffle: 'Acak Playlist',
  'shuffle-disabled': 'Acak Mati',
  'shuffle-variant': 'Acak Lain',
  sigma: 'Simbol Sigma',
  'sigma-lower': 'Sigma Kecil',
  'sign-caution': 'Tanda Hati-hati',
  'sign-direction': 'Papan Arah',
  'sign-text': 'Papan Teks',
  signal: 'Sinyal Jaringan Utama',
  'signal-2g': 'Sinyal 2G',
  'signal-3g': 'Sinyal 3G',
  'signal-4g': 'Sinyal 4G',
  'signal-5g': 'Sinyal 5G',
  'signal-cellular-1': 'Sinyal HP 1',
  'signal-cellular-2': 'Sinyal HP 2',
  'signal-cellular-3': 'Sinyal HP 3',
  'signal-cellular-outline': 'Garis Sinyal HP',
  'signal-hspa': 'Sinyal HSPA',
  'signal-hspa-plus': 'Sinyal HSPA+',
  'signal-off': 'Sinyal Mati Lain',
  'signal-variant': 'Sinyal Lain Lain',
  silverware: 'Sendok Garpu Makan',
  'silverware-clean': 'Sendok Garpu Bersih',
  'silverware-fork': 'Garpu Makan',
  'silverware-fork-knife': 'Sendok Garpu Pisau',
  'silverware-spoon': 'Sendok Makan',
  'silverware-variant': 'Sendok Garpu Lain',
  sim: 'Kartu SIM HP',
  'sim-alert': 'SIM Bahaya',
  'sim-off': 'SIM Mati',
  sitemap: 'Peta Situs',
  'skip-backward': 'Lompat Balik',
  'skip-forward': 'Lompat Maju',
  'skip-next': 'Lanjut Berikutnya',
  'skip-next-circle': 'Lanjut Bulat',
  'skip-previous': 'Kembali Sebelumnya',
  'skip-previous-circle': 'Kembali Bulat',
  skull: 'Tengkorak Bahaya',
  'skull-outline': 'Garis Tengkorak',
  skype: 'Skype Obrolan',
  slack: 'Slack Kerja',
  'slash-forward': 'Garis Miring Maju',
  sledding: 'Main Kereta Salju',
  sleep: 'Mode Tidur Malam',
  'sleep-off': 'Bangun Tidur',
  'slope-downhill': 'Turunan Lereng',
  'slope-uphill': 'Tanjakan Lereng',
  'slot-machine': 'Mesin Jackpot',
  'smart-card': 'Kartu Pintar',
  'smart-card-outline': 'Garis Kartu Pintar',
  smartphone: 'Telepon Pintar Smartphone',
  'smoke-detector': 'Detektor Asap',
  smoking: 'Area Merokok',
  'smoking-off': 'Dilarang Merokok',
  snapchat: 'Snapchat',
  snowflake: 'Butiran Salju',
  'soccer-field': 'Lapangan Bola',
  'sofa-outline': 'Garis Sofa',
  'solar-panel': 'Panel Surya',
  'solar-power': 'Tenaga Surya',
  sort: 'Urutkan Data Utama',
  'sort-alphabetical': 'Urut Abjad A-Z',
  'sort-ascending': 'Urut Naik',
  'sort-descending': 'Urut Turun',
  'sort-numeric': 'Urut Angka',
  soundbar: 'Soundbar Suara',
  'soy-sauce': 'Kecap Asin',
  speaker: 'Speaker Suara',
  'speaker-off': 'Speaker Mati',
  'speaker-wireless': 'Speaker Nirkabel',
  speedometer: 'Kecepatan Kendaraan',
  'speedometer-slow': 'Kecepatan Pelan',
  spellcheck: 'Cek Ejaan',
  'spotify-outline': 'Garis Spotify',
  spotlight: 'Lampu Sorot',
  'spotlight-beam': 'Sinar Lampu Sorot',
  spray: 'Botol Semprot',
  sprout: 'Tunas Tanaman',
  'sprout-outline': 'Garis Tunas',
  square: 'Bentuk Kotak Segi Empat',
  'square-edit-outline': 'Edit Kotak',
  'square-outline': 'Garis Kotak',
  'square-root': 'Akar Kuadrat',
  'stack-exchange': 'Stack Exchange',
  'stack-overflow': 'Stack Overflow',
  stadium: 'Stadion Olahraga',
  'stairs-outline': 'Garis Tangga',
  'star-half': 'Bintang Setengah',
  'star-off': 'Bintang Mati',
  'star-outline': 'Garis Bintang',
  steam: 'Steam Game',
  steering: 'Setir Mobil',
  'step-backward': 'Langkah Mundur',
  'step-forward': 'Langkah Maju',
  'stethoscope-outline': 'Garis Stetoskop',
  sticker: 'Stiker Tempel',
  'sticker-emoji': 'Stiker Emoji',
  stocking: 'Kaos Kaki Natal',
  stop: 'Berhenti Transaksi',
  'stop-circle': 'Berhenti Bulat',
  'store-24-hour': 'Toko 24 Jam',
  'store-outline': 'Garis Toko',
  'stove-outline': 'Garis Kompor',
  strategy: 'Strategi Catur',
  'stretch-to-page': 'Regangkan ke Halaman',
  'string-lights': 'Lampu Hias Tali',
  'subdirectory-arrow-left': 'Sub Menu Kiri',
  'subdirectory-arrow-right': 'Sub Menu Kanan',
  subtitles: 'Teks Film',
  'subtitles-outline': 'Garis Teks Film',
  'subway-variant-outline': 'Garis KRL MRT',
  summit: 'Puncak Gunung',
  'sun-wireless': 'Cas Matahari Nirkabel',
  sunglasses: 'Kacamata Hitam',
  'surround-sound': 'Suara Surround',
  svg: 'Format SVG',
  'swap-vertical': 'Tukar Tegak',
  swim: 'Berenang Olahraga',
  switch: 'Saklar Lampu',
  sword: 'Pedang Tajam',
  'sword-cross': 'Pedang Silang',
  'sync-alert': 'Sinkron Bahaya',
  'sync-off': 'Sinkron Mati',
  tab: 'Tab Halaman',
  'tab-plus': 'Tambah Tab',
  'table-column': 'Kolom Tabel',
  'table-column-plus-after': 'Tambah Kolom Sesudah',
  'table-column-plus-before': 'Tambah Kolom Sebelum',
  'table-column-remove': 'Hapus Kolom',
  'table-column-width': 'Lebar Kolom',
  'table-edit': 'Edit Tabel',
  'table-large': 'Tabel Besar',
  'table-of-contents': 'Daftar Isi',
  'table-plus': 'Tambah Tabel',
  'table-remove': 'Hapus Tabel',
  'table-row': 'Baris Tabel',
  'table-row-height': 'Tinggi Baris',
  'table-row-plus-after': 'Tambah Baris Sesudah',
  'table-row-plus-before': 'Tambah Baris Sebelum',
  'table-row-remove': 'Hapus Baris',
  'table-settings': 'Setelan Tabel',
  tablet: 'Komputer Tablet',
  'tablet-android': 'Tablet Android',
  'tablet-ipad': 'Ipad Apple',
  'taco-outline': 'Garis Kebab',
  tank: 'Mobil Tank',
  'target-account': 'Target Akun',
  'target-variant': 'Target Lain',
  'taxi-outline': 'Garis Taksi',
  'tea-outline': 'Garis Teh',
  teach: 'Mengajar Guru',
  teamviewer: 'Teamviewer',
  telegram: 'Telegram Obrolan',
  television: 'Nonton TV',
  'television-classic': 'TV Tabung Jadul',
  'television-guide': 'Panduan TV',
  'television-off': 'TV Mati',
  'television-play': 'Putar TV',
  'temperature-celsius': 'Suhu Celsius',
  'temperature-fahrenheit': 'Suhu Fahrenheit',
  'temperature-kelvin': 'Suhu Kelvin',
  tennis: 'Main Tenis',
  'tennis-ball': 'Bola Tenis',
  'tent-outline': 'Garis Tenda',
  terrain: 'Medan Tanah',
  'test-tube': 'Tabung Reaksi',
  'test-tube-empty': 'Tabung Reaksi Kosong',
  text: 'Teks Tulisan',
  'text-shadow': 'Bayangan Teks',
  'text-to-speech': 'Teks ke Suara',
  'text-to-speech-off': 'Teks ke Suara Mati',
  'textbox-password': 'Kotak Kata Sandi',
  texture: 'Tekstur Permukaan',
  theater: 'Teater Seni',
  'thermometer-lines': 'Garis Termometer',
  'thought-bubble': 'Gelembung Pikiran',
  'thumb-down': 'Tidak Suka',
  'thumb-down-outline': 'Garis Kurang Suka',
  'thumb-up-outline': 'Garis Bagus',
  'thumbs-up-down': 'Bagus atau Tidak',
  ticket: 'Tiket Masuk',
  'ticket-account': 'Tiket Akun',
  'ticket-confirmation': 'Konfirmasi Tiket',
  'ticket-outline': 'Garis Tiket',
  tie: 'Dasi Kantor',
  tilde: 'Simbol Gelombang Tilde',
  'timer-off': 'Waktu Mati',
  'timer-sand': 'Jam Pasir',
  'timer-sand-empty': 'Jam Pasir Kosong',
  timetable: 'Jadwal Waktu',
  'toggle-off': 'Tombol Geser Mati',
  'toggle-on': 'Tombol Geser Nyala',
  'toilet-outline': 'Garis WC',
  'toolbox-outline': 'Garis Perkakas',
  tooltip: 'Keterangan Alat',
  'tooltip-edit': 'Edit Keterangan',
  'tooltip-image': 'Keterangan Foto',
  'tooltip-plus': 'Tambah Keterangan',
  'tooltip-text': 'Keterangan Teks',
  tooth: 'Gigi Sehat',
  'tower-beach': 'Menara Pantai',
  'tower-fire': 'Menara Api',
  'toy-brick': 'Mainan Lego',
  trackpad: 'Trackpad Laptop',
  'traffic-light': 'Lampu Lalu Lintas',
  'train-variant-outline': 'Garis Kereta Api',
  tram: 'Trem Jalan',
  transcribe: 'Transkrip Suara',
  'transcribe-off': 'Transkrip Mati',
  transfer: 'Transfer Uang Utama',
  'transit-transfer': 'Transit Transfer',
  transition: 'Transisi',
  'transition-masked': 'Transisi Topeng',
  'trash-can-outline-variant': 'Tong Sampah Lain',
  'treasure-chest': 'Peti Harta Karun',
  tree: 'Pohon Rindang',
  'tree-outline': 'Garis Pohon',
  trello: 'Trello Tugas',
  'trending-down': 'Tren Menurun',
  'trending-neutral': 'Tren Datar',
  triangle: 'Bentuk Segitiga',
  'triangle-outline': 'Garis Segitiga',
  'trophy-outline': 'Garis Piala',
  truck: 'Mobil Truk Besar',
  'truck-delivery-outline': 'Garis Kurir',
  'truck-fast-outline': 'Garis Kirim Cepat',
  'tshirt-v': 'Kaos V-Neck',
  'tshirt-v-outline': 'Garis Kaos V-Neck',
  'tumble-dryer': 'Mesin Pengering',
  tune: 'Setelan Suara',
  'tune-vertical': 'Setelan Tegak',
  twitch: 'Twitch Streaming',
  twitter: 'Twitter Sosial',
  uber: 'Uber Perjalanan',
  ubuntu: 'Ubuntu Linux',
  'ultra-high-definition': 'Ultra HD',
  umbrella: 'Payung Hujan',
  'umbrella-outline': 'Garis Payung',
  undo: 'Batal Kembali',
  'undo-variant': 'Batal Kembali Lain',
  'unfold-less-horizontal': 'Lipat Datar',
  'unfold-less-vertical': 'Lipat Tegak',
  'unfold-more-horizontal': 'Buka Datar',
  'unfold-more-vertical': 'Buka Tegak',
  ungroup: 'Pisahkan Grup',
  unity: 'Unity Game Engine',
  unlocked: 'Gembok Terbuka',
  update: 'Pembaruan Aplikasi',
  'upload-network': 'Unggah Jaringan',
  'upload-outline': 'Unggahan',
  usb: 'Kabel USB',
  'vector-arrange-above': 'Susun di Atas',
  'vector-arrange-below': 'Susun di Bawah',
  'vector-circle': 'Vektor Bulat',
  'vector-circle-variant': 'Vektor Bulat Lain',
  'vector-combine': 'Gabung Vektor',
  'vector-curve': 'Kurva Vektor',
  'vector-difference': 'Beda Vektor',
  'vector-difference-ab': 'Beda Vektor AB',
  'vector-difference-ba': 'Beda Vektor BA',
  'vector-intersection': 'Irisan Vektor',
  'vector-line': 'Garis Vektor',
  'vector-point': 'Titik Vektor',
  'vector-polygon': 'Poligon Vektor',
  'vector-polyline': 'Garis Banyak Vektor',
  'vector-rectangle': 'Kotak Vektor',
  'vector-selection': 'Seleksi Vektor',
  'vector-square': 'Kotak Vektor Lain',
  'vector-union': 'Gabungan Vektor',
  vibrate: 'Mode Getar HP',
  'video-off': 'Video Mati',
  'video-outline': 'Garis Video',
  'video-plus': 'Tambah Video',
  'video-switch': 'Ganti Video',
  'view-agenda': 'Tampilan Agenda',
  'view-array': 'Tampilan Array',
  'view-column': 'Tampilan Kolom',
  'view-dashboard': 'Tampilan Dashboard',
  'view-day': 'Tampilan Hari',
  'view-headline': 'Tampilan Berita',
  'view-list': 'Tampilan Daftar',
  'view-module': 'Tampilan Modul',
  'view-quilt': 'Tampilan Selimut',
  'view-stream': 'Tampilan Aliran',
  'view-week': 'Tampilan Minggu',
  vimeo: 'Vimeo Video',
  violin: 'Alat Musik Biola',
  'virtual-reality': 'Virtual Reality VR',
  'visual-studio': 'Visual Studio Kode',
  vk: 'VK Sosial',
  vlc: 'VLC Media Player',
  voice: 'Suara Manusia',
  voicemail: 'Pesan Suara',
  volleyball: 'Bola Voli',
  'volume-low': 'Suara Pelan',
  'volume-medium': 'Suara Sedang',
  'volume-minus': 'Kurangi Suara',
  'volume-mute': 'Suara Mati Mute',
  'volume-off': 'Tanpa Suara',
  'volume-plus': 'Tambah Suara',
  vpn: 'VPN Jaringan Aman',
  vuejs: 'Vue JS Kode',
  'walk-outline': 'Garis Jalan Kaki',
  wall: 'Tembok Bata',
  'wallet-giftcard-outline': 'Garis Voucher Hadiah',
  'wallet-membership-outline': 'Garis Member Kartu',
  'wallet-outline-variant': 'Garis Dompet Lain',
  warehouse: 'Gudang Penyimpanan',
  'washing-machine-outline': 'Garis Mesin Cuci',
  'watch-export': 'Ekspor Jam',
  'watch-import': 'Impor Jam',
  'watch-variant-outline': 'Garis Jam Tangan',
  'water-off': 'Air Mati',
  'water-outline': 'Garis Air',
  'water-percent': 'Persen Air',
  'water-pump-outline': 'Garis Pompa Air',
  'water-variant': 'Air Lain',
  waves: 'Gelombang Laut',
  'weather-cloudy': 'Cuaca Berawan',
  'weather-fog': 'Cuaca Berkabut',
  'weather-hail': 'Cuaca Hujan Es',
  'weather-lightning': 'Cuaca Petir',
  'weather-lightning-rain': 'Cuaca Hujan Petir',
  'weather-night': 'Cuaca Malam Hari',
  'weather-partly-cloudy': 'Cuaca Berawan Sebagian',
  'weather-pouring': 'Cuaca Hujan Deras',
  'weather-rainy': 'Cuaca Hujan Gerimis',
  'weather-snowy': 'Cuaca Berasalju',
  'weather-snowy-rainy': 'Cuaca Hujan Salju',
  'weather-sunset': 'Cuaca Matahari Terbenam',
  'weather-sunset-down': 'Matahari Terbenam Bawah',
  'weather-sunset-up': 'Matahari Terbit',
  'weather-windy': 'Cuaca Berangin',
  'weather-windy-variant': 'Cuaca Angin Lain',
  'web-off': 'Web Mati',
  'webcam-outline': 'Garis Web Cam',
  webhook: 'Web Hook Kode',
  wechat: 'Wechat Obrolan',
  weight: 'Berat Beban',
  'weight-kilogram': 'Berat Kilogram',
  whatsapp: 'Whatsapp Obrolan Utama',
  'wheelchair-accessibility': 'Akses Kursi Roda',
  'white-balance-auto': 'Cahaya Otomatis',
  'white-balance-incandescent': 'Cahaya Pijar',
  'white-balance-iridescent': 'Cahaya Neon',
  'white-balance-sunny-outline': 'Garis Matahari',
  widgets: 'Widget Layar',
  'wifi-off-variant': 'Wifi Mati Lain',
  'wifi-strength-1': 'Wifi Lemah 1',
  'wifi-strength-2': 'Wifi Lemah 2',
  'wifi-strength-3': 'Wifi Kuat 3',
  'wifi-strength-4': 'Wifi Sangat Kuat 4',
  'wifi-strength-off': 'Wifi Mati Total',
  'wifi-strength-outline': 'Garis Wifi',
  wikipedia: 'Wikipedia',
  'window-maximize': 'Jendela Maksimalkan',
  'window-minimize': 'Jendela Minimalkan',
  'window-open': 'Jendela Terbuka',
  'window-restore': 'Jendela Kembalikan',
  wordpress: 'Wordpress Website',
  worker: 'Pekerja Lapangan',
  wrap: 'Bungkus Teks',
  'wrench-outline-variant': 'Garis Obeng Lain',
  xbox: 'Game Xbox',
  'xbox-controller': 'Stik Xbox',
  'xbox-controller-off': 'Stik Xbox Mati',
  xda: 'XDA Developer',
  xing: 'Xing Sosial',
  xml: 'Format XML',
  yeast: 'Ragi Makanan',
  yelp: 'Yelp Review',
  'yin-yang': 'Simbol Yin Yang',
  'youtube-play': 'Putar Youtube',
  'zip-box-outline': 'Garis File Zip',
  'zodiac-aquarius': 'Zodiak Aquarius',
  'zodiac-aries': 'Zodiak Aries',
  'zodiac-cancer': 'Zodiak Cancer',
  'zodiac-capricorn': 'Zodiak Capricorn',
  'zodiac-gemini': 'Zodiak Gemini',
  'zodiac-leo': 'Zodiak Leo',
  'zodiac-libra': 'Zodiak Libra',
  'zodiac-pisces': 'Zodiak Pisces',
  'zodiac-sagittarius': 'Zodiak Sagitarius',
  'zodiac-scorpio': 'Zodiak Scorpio',
  'zodiac-taurus': 'Zodiak Taurus',
  'zodiac-virgo': 'Zodiak Virgo',
};
